[general]
host = "0.0.0.0"
port = 6432
workers = 2
default_pool_size = 32
min_pool_size = 1
checkout_timeout = 30000
idle_timeout = 600000
healthcheck_timeout = 5000
healthcheck_interval = 10000

[[databases]]
name = "postgres"
host = "host.docker.internal"
port = 15433
database_name = "postgres"
user = "postgres"
password = "postgres"
pool_size = 32
min_pool_size = 1
