[package]
name = "herald-infra-wechat"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
herald-domain = { path = "../domain" }
reqwest = { workspace = true, features = ["json"] }
wechat-pay-rust-sdk = "0.2"
serde = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
tracing = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true, features = ["rt"] }
