//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "points_accounts")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: Uuid,
    pub user_id: Uuid,
    pub realm_id: String,
    // Computed total balance (topup_balance + subscription_balance)
    pub total_balance: i64,
    // Type-specific balance fields
    pub topup_balance: i64,
    pub subscription_balance: i64,
    // Type-specific grant tracking
    pub total_topup_granted: i64,
    pub total_subscription_granted: i64,
    // Legacy fields (kept for backward compatibility)
    pub total_recharged: i64,
    pub total_consumed: i64,
    pub status: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::points_transaction::Entity")]
    PointsTransactions,
}

impl Related<super::points_transaction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PointsTransactions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_model_creation() {
        let model = Model {
            id: Uuid::now_v7(),
            user_id: Uuid::now_v7(),
            realm_id: "test-realm".to_string(),
            total_balance: 100,
            topup_balance: 100,
            subscription_balance: 0,
            total_topup_granted: 100,
            total_subscription_granted: 0,
            total_recharged: 1000,
            total_consumed: 900,
            status: "active".to_string(),
            created_at: DateTimeWithTimeZone::from(chrono::Utc::now()),
            updated_at: DateTimeWithTimeZone::from(chrono::Utc::now()),
        };
        assert_eq!(model.total_balance, 100);
    }
}
