//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "points_plan_configs")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: Uuid,
    pub realm_id: String,
    pub plan_id: Uuid,
    pub grant_period_type: String,
    pub points_per_period: i64,
    pub validity_days: i64,
    pub grant_on_subscribe: bool,
    pub max_periods: Option<i64>,
    pub active: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_model_creation() {
        let model = Model {
            id: Uuid::now_v7(),
            realm_id: "test-realm".to_string(),
            plan_id: Uuid::now_v7(),
            grant_period_type: "monthly".to_string(),
            points_per_period: 1000,
            validity_days: 30,
            grant_on_subscribe: true,
            max_periods: None,
            active: true,
            created_at: DateTimeWithTimeZone::from(chrono::Utc::now()),
            updated_at: DateTimeWithTimeZone::from(chrono::Utc::now()),
        };
        assert_eq!(model.grant_period_type, "monthly");
        assert_eq!(model.points_per_period, 1000);
        assert_eq!(model.validity_days, 30);
    }
}
