//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "points_wallets")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: Uuid,
    pub user_id: Uuid,
    pub realm_id: String,
    pub bucket_id: Uuid,
    // Design §1.3 / A7 (BE-D11): the 5 per-type balance columns and the
    // `total_balance` GENERATED column were physically dropped from the base
    // schema. Available balance is now exclusively a derived SUM over
    // `points_credit_ledger`; only the 4 lifetime analytics columns below
    // remain Stored here.
    pub total_topup_granted: i64,
    pub total_subscription_granted: i64,
    // Legacy compatibility field: topup + subscription grants, not all grant types.
    pub total_recharged: i64,
    pub total_consumed: i64,
    pub status: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::credit_bucket::Entity",
        from = "Column::BucketId",
        to = "super::credit_bucket::Column::Id"
    )]
    CreditBucket,
    #[sea_orm(has_many = "super::points_transaction::Entity")]
    PointsTransactions,
}

impl Related<super::credit_bucket::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CreditBucket.def()
    }
}

impl Related<super::points_transaction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PointsTransactions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
