//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "points_transactions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: Uuid,
    pub account_id: Uuid,
    pub user_id: Uuid,
    pub realm_id: String,
    pub r#type: String,
    pub amount: i64,
    pub balance_after: i64,
    // Type-specific balance tracking (optional, for audit trail)
    pub topup_balance_after: Option<i64>,
    pub subscription_balance_after: Option<i64>,
    // Credit type field (optional, for grant/revocation transactions)
    pub credit_type: Option<String>,
    pub description: Option<String>,
    pub client_app_id: Option<Uuid>,
    pub subscription_id: Option<Uuid>,
    pub external_ref_id: Option<String>,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::points_account::Entity",
        from = "Column::AccountId",
        to = "super::points_account::Column::Id"
    )]
    PointsAccount,
}

impl Related<super::points_account::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PointsAccount.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
