/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RealmIdRouteRouteImport } from './routes/$realmId/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RealmIdDeviceRouteImport } from './routes/$realmId/device'
import { Route as RealmIdUserRouteRouteImport } from './routes/$realmId/user/route'
import { Route as RealmIdManageRouteRouteImport } from './routes/$realmId/manage/route'
import { Route as RealmIdAuthRouteRouteImport } from './routes/$realmId/auth/route'
import { Route as RealmIdManageIndexRouteImport } from './routes/$realmId/manage/index'
import { Route as RealmIdDeviceIndexRouteImport } from './routes/$realmId/device.index'
import { Route as RealmIdUserSubscriptionHistoryRouteImport } from './routes/$realmId/user/subscription-history'
import { Route as RealmIdUserSecurityRouteImport } from './routes/$realmId/user/security'
import { Route as RealmIdUserPurchasePointsRouteImport } from './routes/$realmId/user/purchase-points'
import { Route as RealmIdUserProfileRouteImport } from './routes/$realmId/user/profile'
import { Route as RealmIdUserPointsRouteImport } from './routes/$realmId/user/points'
import { Route as RealmIdUserInvoicesRouteImport } from './routes/$realmId/user/invoices'
import { Route as RealmIdSubscriptionMySubscriptionsRouteImport } from './routes/$realmId/subscription/my-subscriptions'
import { Route as RealmIdManageUsersRouteImport } from './routes/$realmId/manage/users'
import { Route as RealmIdManageSubscriptionHistoryRouteImport } from './routes/$realmId/manage/subscription-history'
import { Route as RealmIdManageSubscriptionRouteImport } from './routes/$realmId/manage/subscription'
import { Route as RealmIdManageSettingsRouteImport } from './routes/$realmId/manage/settings'
import { Route as RealmIdManageRolesRouteImport } from './routes/$realmId/manage/roles'
import { Route as RealmIdManageRealmsRouteImport } from './routes/$realmId/manage/realms'
import { Route as RealmIdManageProductsRouteImport } from './routes/$realmId/manage/products'
import { Route as RealmIdManagePointsPackagesRouteImport } from './routes/$realmId/manage/points-packages'
import { Route as RealmIdManagePointsRouteImport } from './routes/$realmId/manage/points'
import { Route as RealmIdManagePermissionsRouteImport } from './routes/$realmId/manage/permissions'
import { Route as RealmIdManageClientAppsRouteImport } from './routes/$realmId/manage/client-apps'
import { Route as RealmIdManageBillingRouteImport } from './routes/$realmId/manage/billing'
import { Route as RealmIdDeviceUserCodeRouteImport } from './routes/$realmId/device.$userCode'
import { Route as RealmIdAuthVerifyEmailRouteImport } from './routes/$realmId/auth/verify-email'
import { Route as RealmIdAuthRegisterRouteImport } from './routes/$realmId/auth/register'
import { Route as RealmIdAuthLoginRouteImport } from './routes/$realmId/auth/login'
import { Route as RealmIdUserSecurityIndexRouteImport } from './routes/$realmId/user/security/index'
import { Route as RealmIdManagePointsPackagesIndexRouteImport } from './routes/$realmId/manage/points-packages/index'
import { Route as RealmIdManageClientAppsIndexRouteImport } from './routes/$realmId/manage/client-apps/index'
import { Route as RealmIdManageBillingIndexRouteImport } from './routes/$realmId/manage/billing/index'
import { Route as RealmIdManageAuditIndexRouteImport } from './routes/$realmId/manage/audit/index'
import { Route as RealmIdUserSecurityTotpSetupRouteImport } from './routes/$realmId/user/security/totp-setup'
import { Route as RealmIdSubscriptionSubscriptionIdHistoryRouteImport } from './routes/$realmId/subscription/$subscriptionId/history'
import { Route as RealmIdManagePointsRealmConfigRouteImport } from './routes/$realmId/manage/points/realm-config'
import { Route as RealmIdManagePointsFreeStatsRouteImport } from './routes/$realmId/manage/points/free-stats'
import { Route as RealmIdManagePointsConfigsRouteImport } from './routes/$realmId/manage/points/configs'
import { Route as RealmIdManagePointsAccountsRouteImport } from './routes/$realmId/manage/points/accounts'
import { Route as RealmIdManagePointsPackagesNewRouteImport } from './routes/$realmId/manage/points-packages/new'
import { Route as RealmIdManageClientAppsNewRouteImport } from './routes/$realmId/manage/client-apps/new'
import { Route as RealmIdManageBillingPlansRouteImport } from './routes/$realmId/manage/billing/plans'
import { Route as RealmIdManageBillingPaymentProvidersRouteImport } from './routes/$realmId/manage/billing/payment-providers'
import { Route as RealmIdManageBillingInvoicesRouteImport } from './routes/$realmId/manage/billing/invoices'
import { Route as RealmIdManageBillingInvoicesIndexRouteImport } from './routes/$realmId/manage/billing/invoices/index'
import { Route as RealmIdManagePointsPackagesPackageIdEditRouteImport } from './routes/$realmId/manage/points-packages/$packageId.edit'
import { Route as RealmIdManageClientAppsClientAppIdEditRouteImport } from './routes/$realmId/manage/client-apps/$clientAppId.edit'
import { Route as RealmIdManageBillingPlansNewRouteImport } from './routes/$realmId/manage/billing/plans/new'
import { Route as RealmIdManageBillingInvoicesNewRouteImport } from './routes/$realmId/manage/billing/invoices/new'
import { Route as RealmIdManageBillingPlansPlanIdEditRouteImport } from './routes/$realmId/manage/billing/plans/$planId.edit'
import { Route as RealmIdManageBillingInvoicesInvoiceIdEditRouteImport } from './routes/$realmId/manage/billing/invoices/$invoiceId.edit'

const RealmIdRouteRoute = RealmIdRouteRouteImport.update({
  id: '/$realmId',
  path: '/$realmId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RealmIdDeviceRoute = RealmIdDeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => RealmIdRouteRoute,
} as any)
const RealmIdUserRouteRoute = RealmIdUserRouteRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => RealmIdRouteRoute,
} as any)
const RealmIdManageRouteRoute = RealmIdManageRouteRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => RealmIdRouteRoute,
} as any)
const RealmIdAuthRouteRoute = RealmIdAuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => RealmIdRouteRoute,
} as any)
const RealmIdManageIndexRoute = RealmIdManageIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RealmIdManageRouteRoute,
} as any)
const RealmIdDeviceIndexRoute = RealmIdDeviceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RealmIdDeviceRoute,
} as any)
const RealmIdUserSubscriptionHistoryRoute =
  RealmIdUserSubscriptionHistoryRouteImport.update({
    id: '/subscription-history',
    path: '/subscription-history',
    getParentRoute: () => RealmIdUserRouteRoute,
  } as any)
const RealmIdUserSecurityRoute = RealmIdUserSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => RealmIdUserRouteRoute,
} as any)
const RealmIdUserPurchasePointsRoute =
  RealmIdUserPurchasePointsRouteImport.update({
    id: '/purchase-points',
    path: '/purchase-points',
    getParentRoute: () => RealmIdUserRouteRoute,
  } as any)
const RealmIdUserProfileRoute = RealmIdUserProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => RealmIdUserRouteRoute,
} as any)
const RealmIdUserPointsRoute = RealmIdUserPointsRouteImport.update({
  id: '/points',
  path: '/points',
  getParentRoute: () => RealmIdUserRouteRoute,
} as any)
const RealmIdUserInvoicesRoute = RealmIdUserInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => RealmIdUserRouteRoute,
} as any)
const RealmIdSubscriptionMySubscriptionsRoute =
  RealmIdSubscriptionMySubscriptionsRouteImport.update({
    id: '/subscription/my-subscriptions',
    path: '/subscription/my-subscriptions',
    getParentRoute: () => RealmIdRouteRoute,
  } as any)
const RealmIdManageUsersRoute = RealmIdManageUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => RealmIdManageRouteRoute,
} as any)
const RealmIdManageSubscriptionHistoryRoute =
  RealmIdManageSubscriptionHistoryRouteImport.update({
    id: '/subscription-history',
    path: '/subscription-history',
    getParentRoute: () => RealmIdManageRouteRoute,
  } as any)
const RealmIdManageSubscriptionRoute =
  RealmIdManageSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => RealmIdManageRouteRoute,
  } as any)
const RealmIdManageSettingsRoute = RealmIdManageSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => RealmIdManageRouteRoute,
} as any)
const RealmIdManageRolesRoute = RealmIdManageRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => RealmIdManageRouteRoute,
} as any)
const RealmIdManageRealmsRoute = RealmIdManageRealmsRouteImport.update({
  id: '/realms',
  path: '/realms',
  getParentRoute: () => RealmIdManageRouteRoute,
} as any)
const RealmIdManageProductsRoute = RealmIdManageProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => RealmIdManageRouteRoute,
} as any)
const RealmIdManagePointsPackagesRoute =
  RealmIdManagePointsPackagesRouteImport.update({
    id: '/points-packages',
    path: '/points-packages',
    getParentRoute: () => RealmIdManageRouteRoute,
  } as any)
const RealmIdManagePointsRoute = RealmIdManagePointsRouteImport.update({
  id: '/points',
  path: '/points',
  getParentRoute: () => RealmIdManageRouteRoute,
} as any)
const RealmIdManagePermissionsRoute =
  RealmIdManagePermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => RealmIdManageRouteRoute,
  } as any)
const RealmIdManageClientAppsRoute = RealmIdManageClientAppsRouteImport.update({
  id: '/client-apps',
  path: '/client-apps',
  getParentRoute: () => RealmIdManageRouteRoute,
} as any)
const RealmIdManageBillingRoute = RealmIdManageBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => RealmIdManageRouteRoute,
} as any)
const RealmIdDeviceUserCodeRoute = RealmIdDeviceUserCodeRouteImport.update({
  id: '/$userCode',
  path: '/$userCode',
  getParentRoute: () => RealmIdDeviceRoute,
} as any)
const RealmIdAuthVerifyEmailRoute = RealmIdAuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => RealmIdAuthRouteRoute,
} as any)
const RealmIdAuthRegisterRoute = RealmIdAuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => RealmIdAuthRouteRoute,
} as any)
const RealmIdAuthLoginRoute = RealmIdAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => RealmIdAuthRouteRoute,
} as any)
const RealmIdUserSecurityIndexRoute =
  RealmIdUserSecurityIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => RealmIdUserSecurityRoute,
  } as any)
const RealmIdManagePointsPackagesIndexRoute =
  RealmIdManagePointsPackagesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => RealmIdManagePointsPackagesRoute,
  } as any)
const RealmIdManageClientAppsIndexRoute =
  RealmIdManageClientAppsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => RealmIdManageClientAppsRoute,
  } as any)
const RealmIdManageBillingIndexRoute =
  RealmIdManageBillingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => RealmIdManageBillingRoute,
  } as any)
const RealmIdManageAuditIndexRoute = RealmIdManageAuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => RealmIdManageRouteRoute,
} as any)
const RealmIdUserSecurityTotpSetupRoute =
  RealmIdUserSecurityTotpSetupRouteImport.update({
    id: '/totp-setup',
    path: '/totp-setup',
    getParentRoute: () => RealmIdUserSecurityRoute,
  } as any)
const RealmIdSubscriptionSubscriptionIdHistoryRoute =
  RealmIdSubscriptionSubscriptionIdHistoryRouteImport.update({
    id: '/subscription/$subscriptionId/history',
    path: '/subscription/$subscriptionId/history',
    getParentRoute: () => RealmIdRouteRoute,
  } as any)
const RealmIdManagePointsRealmConfigRoute =
  RealmIdManagePointsRealmConfigRouteImport.update({
    id: '/realm-config',
    path: '/realm-config',
    getParentRoute: () => RealmIdManagePointsRoute,
  } as any)
const RealmIdManagePointsFreeStatsRoute =
  RealmIdManagePointsFreeStatsRouteImport.update({
    id: '/free-stats',
    path: '/free-stats',
    getParentRoute: () => RealmIdManagePointsRoute,
  } as any)
const RealmIdManagePointsConfigsRoute =
  RealmIdManagePointsConfigsRouteImport.update({
    id: '/configs',
    path: '/configs',
    getParentRoute: () => RealmIdManagePointsRoute,
  } as any)
const RealmIdManagePointsAccountsRoute =
  RealmIdManagePointsAccountsRouteImport.update({
    id: '/accounts',
    path: '/accounts',
    getParentRoute: () => RealmIdManagePointsRoute,
  } as any)
const RealmIdManagePointsPackagesNewRoute =
  RealmIdManagePointsPackagesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => RealmIdManagePointsPackagesRoute,
  } as any)
const RealmIdManageClientAppsNewRoute =
  RealmIdManageClientAppsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => RealmIdManageClientAppsRoute,
  } as any)
const RealmIdManageBillingPlansRoute =
  RealmIdManageBillingPlansRouteImport.update({
    id: '/plans',
    path: '/plans',
    getParentRoute: () => RealmIdManageBillingRoute,
  } as any)
const RealmIdManageBillingPaymentProvidersRoute =
  RealmIdManageBillingPaymentProvidersRouteImport.update({
    id: '/payment-providers',
    path: '/payment-providers',
    getParentRoute: () => RealmIdManageBillingRoute,
  } as any)
const RealmIdManageBillingInvoicesRoute =
  RealmIdManageBillingInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => RealmIdManageBillingRoute,
  } as any)
const RealmIdManageBillingInvoicesIndexRoute =
  RealmIdManageBillingInvoicesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => RealmIdManageBillingInvoicesRoute,
  } as any)
const RealmIdManagePointsPackagesPackageIdEditRoute =
  RealmIdManagePointsPackagesPackageIdEditRouteImport.update({
    id: '/$packageId/edit',
    path: '/$packageId/edit',
    getParentRoute: () => RealmIdManagePointsPackagesRoute,
  } as any)
const RealmIdManageClientAppsClientAppIdEditRoute =
  RealmIdManageClientAppsClientAppIdEditRouteImport.update({
    id: '/$clientAppId/edit',
    path: '/$clientAppId/edit',
    getParentRoute: () => RealmIdManageClientAppsRoute,
  } as any)
const RealmIdManageBillingPlansNewRoute =
  RealmIdManageBillingPlansNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => RealmIdManageBillingPlansRoute,
  } as any)
const RealmIdManageBillingInvoicesNewRoute =
  RealmIdManageBillingInvoicesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => RealmIdManageBillingInvoicesRoute,
  } as any)
const RealmIdManageBillingPlansPlanIdEditRoute =
  RealmIdManageBillingPlansPlanIdEditRouteImport.update({
    id: '/$planId/edit',
    path: '/$planId/edit',
    getParentRoute: () => RealmIdManageBillingPlansRoute,
  } as any)
const RealmIdManageBillingInvoicesInvoiceIdEditRoute =
  RealmIdManageBillingInvoicesInvoiceIdEditRouteImport.update({
    id: '/$invoiceId/edit',
    path: '/$invoiceId/edit',
    getParentRoute: () => RealmIdManageBillingInvoicesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$realmId': typeof RealmIdRouteRouteWithChildren
  '/$realmId/auth': typeof RealmIdAuthRouteRouteWithChildren
  '/$realmId/manage': typeof RealmIdManageRouteRouteWithChildren
  '/$realmId/user': typeof RealmIdUserRouteRouteWithChildren
  '/$realmId/device': typeof RealmIdDeviceRouteWithChildren
  '/$realmId/auth/login': typeof RealmIdAuthLoginRoute
  '/$realmId/auth/register': typeof RealmIdAuthRegisterRoute
  '/$realmId/auth/verify-email': typeof RealmIdAuthVerifyEmailRoute
  '/$realmId/device/$userCode': typeof RealmIdDeviceUserCodeRoute
  '/$realmId/manage/billing': typeof RealmIdManageBillingRouteWithChildren
  '/$realmId/manage/client-apps': typeof RealmIdManageClientAppsRouteWithChildren
  '/$realmId/manage/permissions': typeof RealmIdManagePermissionsRoute
  '/$realmId/manage/points': typeof RealmIdManagePointsRouteWithChildren
  '/$realmId/manage/points-packages': typeof RealmIdManagePointsPackagesRouteWithChildren
  '/$realmId/manage/products': typeof RealmIdManageProductsRoute
  '/$realmId/manage/realms': typeof RealmIdManageRealmsRoute
  '/$realmId/manage/roles': typeof RealmIdManageRolesRoute
  '/$realmId/manage/settings': typeof RealmIdManageSettingsRoute
  '/$realmId/manage/subscription': typeof RealmIdManageSubscriptionRoute
  '/$realmId/manage/subscription-history': typeof RealmIdManageSubscriptionHistoryRoute
  '/$realmId/manage/users': typeof RealmIdManageUsersRoute
  '/$realmId/subscription/my-subscriptions': typeof RealmIdSubscriptionMySubscriptionsRoute
  '/$realmId/user/invoices': typeof RealmIdUserInvoicesRoute
  '/$realmId/user/points': typeof RealmIdUserPointsRoute
  '/$realmId/user/profile': typeof RealmIdUserProfileRoute
  '/$realmId/user/purchase-points': typeof RealmIdUserPurchasePointsRoute
  '/$realmId/user/security': typeof RealmIdUserSecurityRouteWithChildren
  '/$realmId/user/subscription-history': typeof RealmIdUserSubscriptionHistoryRoute
  '/$realmId/device/': typeof RealmIdDeviceIndexRoute
  '/$realmId/manage/': typeof RealmIdManageIndexRoute
  '/$realmId/manage/billing/invoices': typeof RealmIdManageBillingInvoicesRouteWithChildren
  '/$realmId/manage/billing/payment-providers': typeof RealmIdManageBillingPaymentProvidersRoute
  '/$realmId/manage/billing/plans': typeof RealmIdManageBillingPlansRouteWithChildren
  '/$realmId/manage/client-apps/new': typeof RealmIdManageClientAppsNewRoute
  '/$realmId/manage/points-packages/new': typeof RealmIdManagePointsPackagesNewRoute
  '/$realmId/manage/points/accounts': typeof RealmIdManagePointsAccountsRoute
  '/$realmId/manage/points/configs': typeof RealmIdManagePointsConfigsRoute
  '/$realmId/manage/points/free-stats': typeof RealmIdManagePointsFreeStatsRoute
  '/$realmId/manage/points/realm-config': typeof RealmIdManagePointsRealmConfigRoute
  '/$realmId/subscription/$subscriptionId/history': typeof RealmIdSubscriptionSubscriptionIdHistoryRoute
  '/$realmId/user/security/totp-setup': typeof RealmIdUserSecurityTotpSetupRoute
  '/$realmId/manage/audit/': typeof RealmIdManageAuditIndexRoute
  '/$realmId/manage/billing/': typeof RealmIdManageBillingIndexRoute
  '/$realmId/manage/client-apps/': typeof RealmIdManageClientAppsIndexRoute
  '/$realmId/manage/points-packages/': typeof RealmIdManagePointsPackagesIndexRoute
  '/$realmId/user/security/': typeof RealmIdUserSecurityIndexRoute
  '/$realmId/manage/billing/invoices/new': typeof RealmIdManageBillingInvoicesNewRoute
  '/$realmId/manage/billing/plans/new': typeof RealmIdManageBillingPlansNewRoute
  '/$realmId/manage/client-apps/$clientAppId/edit': typeof RealmIdManageClientAppsClientAppIdEditRoute
  '/$realmId/manage/points-packages/$packageId/edit': typeof RealmIdManagePointsPackagesPackageIdEditRoute
  '/$realmId/manage/billing/invoices/': typeof RealmIdManageBillingInvoicesIndexRoute
  '/$realmId/manage/billing/invoices/$invoiceId/edit': typeof RealmIdManageBillingInvoicesInvoiceIdEditRoute
  '/$realmId/manage/billing/plans/$planId/edit': typeof RealmIdManageBillingPlansPlanIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$realmId': typeof RealmIdRouteRouteWithChildren
  '/$realmId/auth': typeof RealmIdAuthRouteRouteWithChildren
  '/$realmId/user': typeof RealmIdUserRouteRouteWithChildren
  '/$realmId/auth/login': typeof RealmIdAuthLoginRoute
  '/$realmId/auth/register': typeof RealmIdAuthRegisterRoute
  '/$realmId/auth/verify-email': typeof RealmIdAuthVerifyEmailRoute
  '/$realmId/device/$userCode': typeof RealmIdDeviceUserCodeRoute
  '/$realmId/manage/permissions': typeof RealmIdManagePermissionsRoute
  '/$realmId/manage/points': typeof RealmIdManagePointsRouteWithChildren
  '/$realmId/manage/products': typeof RealmIdManageProductsRoute
  '/$realmId/manage/realms': typeof RealmIdManageRealmsRoute
  '/$realmId/manage/roles': typeof RealmIdManageRolesRoute
  '/$realmId/manage/settings': typeof RealmIdManageSettingsRoute
  '/$realmId/manage/subscription': typeof RealmIdManageSubscriptionRoute
  '/$realmId/manage/subscription-history': typeof RealmIdManageSubscriptionHistoryRoute
  '/$realmId/manage/users': typeof RealmIdManageUsersRoute
  '/$realmId/subscription/my-subscriptions': typeof RealmIdSubscriptionMySubscriptionsRoute
  '/$realmId/user/invoices': typeof RealmIdUserInvoicesRoute
  '/$realmId/user/points': typeof RealmIdUserPointsRoute
  '/$realmId/user/profile': typeof RealmIdUserProfileRoute
  '/$realmId/user/purchase-points': typeof RealmIdUserPurchasePointsRoute
  '/$realmId/user/subscription-history': typeof RealmIdUserSubscriptionHistoryRoute
  '/$realmId/device': typeof RealmIdDeviceIndexRoute
  '/$realmId/manage': typeof RealmIdManageIndexRoute
  '/$realmId/manage/billing/payment-providers': typeof RealmIdManageBillingPaymentProvidersRoute
  '/$realmId/manage/billing/plans': typeof RealmIdManageBillingPlansRouteWithChildren
  '/$realmId/manage/client-apps/new': typeof RealmIdManageClientAppsNewRoute
  '/$realmId/manage/points-packages/new': typeof RealmIdManagePointsPackagesNewRoute
  '/$realmId/manage/points/accounts': typeof RealmIdManagePointsAccountsRoute
  '/$realmId/manage/points/configs': typeof RealmIdManagePointsConfigsRoute
  '/$realmId/manage/points/free-stats': typeof RealmIdManagePointsFreeStatsRoute
  '/$realmId/manage/points/realm-config': typeof RealmIdManagePointsRealmConfigRoute
  '/$realmId/subscription/$subscriptionId/history': typeof RealmIdSubscriptionSubscriptionIdHistoryRoute
  '/$realmId/user/security/totp-setup': typeof RealmIdUserSecurityTotpSetupRoute
  '/$realmId/manage/audit': typeof RealmIdManageAuditIndexRoute
  '/$realmId/manage/billing': typeof RealmIdManageBillingIndexRoute
  '/$realmId/manage/client-apps': typeof RealmIdManageClientAppsIndexRoute
  '/$realmId/manage/points-packages': typeof RealmIdManagePointsPackagesIndexRoute
  '/$realmId/user/security': typeof RealmIdUserSecurityIndexRoute
  '/$realmId/manage/billing/invoices/new': typeof RealmIdManageBillingInvoicesNewRoute
  '/$realmId/manage/billing/plans/new': typeof RealmIdManageBillingPlansNewRoute
  '/$realmId/manage/client-apps/$clientAppId/edit': typeof RealmIdManageClientAppsClientAppIdEditRoute
  '/$realmId/manage/points-packages/$packageId/edit': typeof RealmIdManagePointsPackagesPackageIdEditRoute
  '/$realmId/manage/billing/invoices': typeof RealmIdManageBillingInvoicesIndexRoute
  '/$realmId/manage/billing/invoices/$invoiceId/edit': typeof RealmIdManageBillingInvoicesInvoiceIdEditRoute
  '/$realmId/manage/billing/plans/$planId/edit': typeof RealmIdManageBillingPlansPlanIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$realmId': typeof RealmIdRouteRouteWithChildren
  '/$realmId/auth': typeof RealmIdAuthRouteRouteWithChildren
  '/$realmId/manage': typeof RealmIdManageRouteRouteWithChildren
  '/$realmId/user': typeof RealmIdUserRouteRouteWithChildren
  '/$realmId/device': typeof RealmIdDeviceRouteWithChildren
  '/$realmId/auth/login': typeof RealmIdAuthLoginRoute
  '/$realmId/auth/register': typeof RealmIdAuthRegisterRoute
  '/$realmId/auth/verify-email': typeof RealmIdAuthVerifyEmailRoute
  '/$realmId/device/$userCode': typeof RealmIdDeviceUserCodeRoute
  '/$realmId/manage/billing': typeof RealmIdManageBillingRouteWithChildren
  '/$realmId/manage/client-apps': typeof RealmIdManageClientAppsRouteWithChildren
  '/$realmId/manage/permissions': typeof RealmIdManagePermissionsRoute
  '/$realmId/manage/points': typeof RealmIdManagePointsRouteWithChildren
  '/$realmId/manage/points-packages': typeof RealmIdManagePointsPackagesRouteWithChildren
  '/$realmId/manage/products': typeof RealmIdManageProductsRoute
  '/$realmId/manage/realms': typeof RealmIdManageRealmsRoute
  '/$realmId/manage/roles': typeof RealmIdManageRolesRoute
  '/$realmId/manage/settings': typeof RealmIdManageSettingsRoute
  '/$realmId/manage/subscription': typeof RealmIdManageSubscriptionRoute
  '/$realmId/manage/subscription-history': typeof RealmIdManageSubscriptionHistoryRoute
  '/$realmId/manage/users': typeof RealmIdManageUsersRoute
  '/$realmId/subscription/my-subscriptions': typeof RealmIdSubscriptionMySubscriptionsRoute
  '/$realmId/user/invoices': typeof RealmIdUserInvoicesRoute
  '/$realmId/user/points': typeof RealmIdUserPointsRoute
  '/$realmId/user/profile': typeof RealmIdUserProfileRoute
  '/$realmId/user/purchase-points': typeof RealmIdUserPurchasePointsRoute
  '/$realmId/user/security': typeof RealmIdUserSecurityRouteWithChildren
  '/$realmId/user/subscription-history': typeof RealmIdUserSubscriptionHistoryRoute
  '/$realmId/device/': typeof RealmIdDeviceIndexRoute
  '/$realmId/manage/': typeof RealmIdManageIndexRoute
  '/$realmId/manage/billing/invoices': typeof RealmIdManageBillingInvoicesRouteWithChildren
  '/$realmId/manage/billing/payment-providers': typeof RealmIdManageBillingPaymentProvidersRoute
  '/$realmId/manage/billing/plans': typeof RealmIdManageBillingPlansRouteWithChildren
  '/$realmId/manage/client-apps/new': typeof RealmIdManageClientAppsNewRoute
  '/$realmId/manage/points-packages/new': typeof RealmIdManagePointsPackagesNewRoute
  '/$realmId/manage/points/accounts': typeof RealmIdManagePointsAccountsRoute
  '/$realmId/manage/points/configs': typeof RealmIdManagePointsConfigsRoute
  '/$realmId/manage/points/free-stats': typeof RealmIdManagePointsFreeStatsRoute
  '/$realmId/manage/points/realm-config': typeof RealmIdManagePointsRealmConfigRoute
  '/$realmId/subscription/$subscriptionId/history': typeof RealmIdSubscriptionSubscriptionIdHistoryRoute
  '/$realmId/user/security/totp-setup': typeof RealmIdUserSecurityTotpSetupRoute
  '/$realmId/manage/audit/': typeof RealmIdManageAuditIndexRoute
  '/$realmId/manage/billing/': typeof RealmIdManageBillingIndexRoute
  '/$realmId/manage/client-apps/': typeof RealmIdManageClientAppsIndexRoute
  '/$realmId/manage/points-packages/': typeof RealmIdManagePointsPackagesIndexRoute
  '/$realmId/user/security/': typeof RealmIdUserSecurityIndexRoute
  '/$realmId/manage/billing/invoices/new': typeof RealmIdManageBillingInvoicesNewRoute
  '/$realmId/manage/billing/plans/new': typeof RealmIdManageBillingPlansNewRoute
  '/$realmId/manage/client-apps/$clientAppId/edit': typeof RealmIdManageClientAppsClientAppIdEditRoute
  '/$realmId/manage/points-packages/$packageId/edit': typeof RealmIdManagePointsPackagesPackageIdEditRoute
  '/$realmId/manage/billing/invoices/': typeof RealmIdManageBillingInvoicesIndexRoute
  '/$realmId/manage/billing/invoices/$invoiceId/edit': typeof RealmIdManageBillingInvoicesInvoiceIdEditRoute
  '/$realmId/manage/billing/plans/$planId/edit': typeof RealmIdManageBillingPlansPlanIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$realmId'
    | '/$realmId/auth'
    | '/$realmId/manage'
    | '/$realmId/user'
    | '/$realmId/device'
    | '/$realmId/auth/login'
    | '/$realmId/auth/register'
    | '/$realmId/auth/verify-email'
    | '/$realmId/device/$userCode'
    | '/$realmId/manage/billing'
    | '/$realmId/manage/client-apps'
    | '/$realmId/manage/permissions'
    | '/$realmId/manage/points'
    | '/$realmId/manage/points-packages'
    | '/$realmId/manage/products'
    | '/$realmId/manage/realms'
    | '/$realmId/manage/roles'
    | '/$realmId/manage/settings'
    | '/$realmId/manage/subscription'
    | '/$realmId/manage/subscription-history'
    | '/$realmId/manage/users'
    | '/$realmId/subscription/my-subscriptions'
    | '/$realmId/user/invoices'
    | '/$realmId/user/points'
    | '/$realmId/user/profile'
    | '/$realmId/user/purchase-points'
    | '/$realmId/user/security'
    | '/$realmId/user/subscription-history'
    | '/$realmId/device/'
    | '/$realmId/manage/'
    | '/$realmId/manage/billing/invoices'
    | '/$realmId/manage/billing/payment-providers'
    | '/$realmId/manage/billing/plans'
    | '/$realmId/manage/client-apps/new'
    | '/$realmId/manage/points-packages/new'
    | '/$realmId/manage/points/accounts'
    | '/$realmId/manage/points/configs'
    | '/$realmId/manage/points/free-stats'
    | '/$realmId/manage/points/realm-config'
    | '/$realmId/subscription/$subscriptionId/history'
    | '/$realmId/user/security/totp-setup'
    | '/$realmId/manage/audit/'
    | '/$realmId/manage/billing/'
    | '/$realmId/manage/client-apps/'
    | '/$realmId/manage/points-packages/'
    | '/$realmId/user/security/'
    | '/$realmId/manage/billing/invoices/new'
    | '/$realmId/manage/billing/plans/new'
    | '/$realmId/manage/client-apps/$clientAppId/edit'
    | '/$realmId/manage/points-packages/$packageId/edit'
    | '/$realmId/manage/billing/invoices/'
    | '/$realmId/manage/billing/invoices/$invoiceId/edit'
    | '/$realmId/manage/billing/plans/$planId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$realmId'
    | '/$realmId/auth'
    | '/$realmId/user'
    | '/$realmId/auth/login'
    | '/$realmId/auth/register'
    | '/$realmId/auth/verify-email'
    | '/$realmId/device/$userCode'
    | '/$realmId/manage/permissions'
    | '/$realmId/manage/points'
    | '/$realmId/manage/products'
    | '/$realmId/manage/realms'
    | '/$realmId/manage/roles'
    | '/$realmId/manage/settings'
    | '/$realmId/manage/subscription'
    | '/$realmId/manage/subscription-history'
    | '/$realmId/manage/users'
    | '/$realmId/subscription/my-subscriptions'
    | '/$realmId/user/invoices'
    | '/$realmId/user/points'
    | '/$realmId/user/profile'
    | '/$realmId/user/purchase-points'
    | '/$realmId/user/subscription-history'
    | '/$realmId/device'
    | '/$realmId/manage'
    | '/$realmId/manage/billing/payment-providers'
    | '/$realmId/manage/billing/plans'
    | '/$realmId/manage/client-apps/new'
    | '/$realmId/manage/points-packages/new'
    | '/$realmId/manage/points/accounts'
    | '/$realmId/manage/points/configs'
    | '/$realmId/manage/points/free-stats'
    | '/$realmId/manage/points/realm-config'
    | '/$realmId/subscription/$subscriptionId/history'
    | '/$realmId/user/security/totp-setup'
    | '/$realmId/manage/audit'
    | '/$realmId/manage/billing'
    | '/$realmId/manage/client-apps'
    | '/$realmId/manage/points-packages'
    | '/$realmId/user/security'
    | '/$realmId/manage/billing/invoices/new'
    | '/$realmId/manage/billing/plans/new'
    | '/$realmId/manage/client-apps/$clientAppId/edit'
    | '/$realmId/manage/points-packages/$packageId/edit'
    | '/$realmId/manage/billing/invoices'
    | '/$realmId/manage/billing/invoices/$invoiceId/edit'
    | '/$realmId/manage/billing/plans/$planId/edit'
  id:
    | '__root__'
    | '/'
    | '/$realmId'
    | '/$realmId/auth'
    | '/$realmId/manage'
    | '/$realmId/user'
    | '/$realmId/device'
    | '/$realmId/auth/login'
    | '/$realmId/auth/register'
    | '/$realmId/auth/verify-email'
    | '/$realmId/device/$userCode'
    | '/$realmId/manage/billing'
    | '/$realmId/manage/client-apps'
    | '/$realmId/manage/permissions'
    | '/$realmId/manage/points'
    | '/$realmId/manage/points-packages'
    | '/$realmId/manage/products'
    | '/$realmId/manage/realms'
    | '/$realmId/manage/roles'
    | '/$realmId/manage/settings'
    | '/$realmId/manage/subscription'
    | '/$realmId/manage/subscription-history'
    | '/$realmId/manage/users'
    | '/$realmId/subscription/my-subscriptions'
    | '/$realmId/user/invoices'
    | '/$realmId/user/points'
    | '/$realmId/user/profile'
    | '/$realmId/user/purchase-points'
    | '/$realmId/user/security'
    | '/$realmId/user/subscription-history'
    | '/$realmId/device/'
    | '/$realmId/manage/'
    | '/$realmId/manage/billing/invoices'
    | '/$realmId/manage/billing/payment-providers'
    | '/$realmId/manage/billing/plans'
    | '/$realmId/manage/client-apps/new'
    | '/$realmId/manage/points-packages/new'
    | '/$realmId/manage/points/accounts'
    | '/$realmId/manage/points/configs'
    | '/$realmId/manage/points/free-stats'
    | '/$realmId/manage/points/realm-config'
    | '/$realmId/subscription/$subscriptionId/history'
    | '/$realmId/user/security/totp-setup'
    | '/$realmId/manage/audit/'
    | '/$realmId/manage/billing/'
    | '/$realmId/manage/client-apps/'
    | '/$realmId/manage/points-packages/'
    | '/$realmId/user/security/'
    | '/$realmId/manage/billing/invoices/new'
    | '/$realmId/manage/billing/plans/new'
    | '/$realmId/manage/client-apps/$clientAppId/edit'
    | '/$realmId/manage/points-packages/$packageId/edit'
    | '/$realmId/manage/billing/invoices/'
    | '/$realmId/manage/billing/invoices/$invoiceId/edit'
    | '/$realmId/manage/billing/plans/$planId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RealmIdRouteRoute: typeof RealmIdRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$realmId': {
      id: '/$realmId'
      path: '/$realmId'
      fullPath: '/$realmId'
      preLoaderRoute: typeof RealmIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$realmId/device': {
      id: '/$realmId/device'
      path: '/device'
      fullPath: '/$realmId/device'
      preLoaderRoute: typeof RealmIdDeviceRouteImport
      parentRoute: typeof RealmIdRouteRoute
    }
    '/$realmId/user': {
      id: '/$realmId/user'
      path: '/user'
      fullPath: '/$realmId/user'
      preLoaderRoute: typeof RealmIdUserRouteRouteImport
      parentRoute: typeof RealmIdRouteRoute
    }
    '/$realmId/manage': {
      id: '/$realmId/manage'
      path: '/manage'
      fullPath: '/$realmId/manage'
      preLoaderRoute: typeof RealmIdManageRouteRouteImport
      parentRoute: typeof RealmIdRouteRoute
    }
    '/$realmId/auth': {
      id: '/$realmId/auth'
      path: '/auth'
      fullPath: '/$realmId/auth'
      preLoaderRoute: typeof RealmIdAuthRouteRouteImport
      parentRoute: typeof RealmIdRouteRoute
    }
    '/$realmId/manage/': {
      id: '/$realmId/manage/'
      path: '/'
      fullPath: '/$realmId/manage/'
      preLoaderRoute: typeof RealmIdManageIndexRouteImport
      parentRoute: typeof RealmIdManageRouteRoute
    }
    '/$realmId/device/': {
      id: '/$realmId/device/'
      path: '/'
      fullPath: '/$realmId/device/'
      preLoaderRoute: typeof RealmIdDeviceIndexRouteImport
      parentRoute: typeof RealmIdDeviceRoute
    }
    '/$realmId/user/subscription-history': {
      id: '/$realmId/user/subscription-history'
      path: '/subscription-history'
      fullPath: '/$realmId/user/subscription-history'
      preLoaderRoute: typeof RealmIdUserSubscriptionHistoryRouteImport
      parentRoute: typeof RealmIdUserRouteRoute
    }
    '/$realmId/user/security': {
      id: '/$realmId/user/security'
      path: '/security'
      fullPath: '/$realmId/user/security'
      preLoaderRoute: typeof RealmIdUserSecurityRouteImport
      parentRoute: typeof RealmIdUserRouteRoute
    }
    '/$realmId/user/purchase-points': {
      id: '/$realmId/user/purchase-points'
      path: '/purchase-points'
      fullPath: '/$realmId/user/purchase-points'
      preLoaderRoute: typeof RealmIdUserPurchasePointsRouteImport
      parentRoute: typeof RealmIdUserRouteRoute
    }
    '/$realmId/user/profile': {
      id: '/$realmId/user/profile'
      path: '/profile'
      fullPath: '/$realmId/user/profile'
      preLoaderRoute: typeof RealmIdUserProfileRouteImport
      parentRoute: typeof RealmIdUserRouteRoute
    }
    '/$realmId/user/points': {
      id: '/$realmId/user/points'
      path: '/points'
      fullPath: '/$realmId/user/points'
      preLoaderRoute: typeof RealmIdUserPointsRouteImport
      parentRoute: typeof RealmIdUserRouteRoute
    }
    '/$realmId/user/invoices': {
      id: '/$realmId/user/invoices'
      path: '/invoices'
      fullPath: '/$realmId/user/invoices'
      preLoaderRoute: typeof RealmIdUserInvoicesRouteImport
      parentRoute: typeof RealmIdUserRouteRoute
    }
    '/$realmId/subscription/my-subscriptions': {
      id: '/$realmId/subscription/my-subscriptions'
      path: '/subscription/my-subscriptions'
      fullPath: '/$realmId/subscription/my-subscriptions'
      preLoaderRoute: typeof RealmIdSubscriptionMySubscriptionsRouteImport
      parentRoute: typeof RealmIdRouteRoute
    }
    '/$realmId/manage/users': {
      id: '/$realmId/manage/users'
      path: '/users'
      fullPath: '/$realmId/manage/users'
      preLoaderRoute: typeof RealmIdManageUsersRouteImport
      parentRoute: typeof RealmIdManageRouteRoute
    }
    '/$realmId/manage/subscription-history': {
      id: '/$realmId/manage/subscription-history'
      path: '/subscription-history'
      fullPath: '/$realmId/manage/subscription-history'
      preLoaderRoute: typeof RealmIdManageSubscriptionHistoryRouteImport
      parentRoute: typeof RealmIdManageRouteRoute
    }
    '/$realmId/manage/subscription': {
      id: '/$realmId/manage/subscription'
      path: '/subscription'
      fullPath: '/$realmId/manage/subscription'
      preLoaderRoute: typeof RealmIdManageSubscriptionRouteImport
      parentRoute: typeof RealmIdManageRouteRoute
    }
    '/$realmId/manage/settings': {
      id: '/$realmId/manage/settings'
      path: '/settings'
      fullPath: '/$realmId/manage/settings'
      preLoaderRoute: typeof RealmIdManageSettingsRouteImport
      parentRoute: typeof RealmIdManageRouteRoute
    }
    '/$realmId/manage/roles': {
      id: '/$realmId/manage/roles'
      path: '/roles'
      fullPath: '/$realmId/manage/roles'
      preLoaderRoute: typeof RealmIdManageRolesRouteImport
      parentRoute: typeof RealmIdManageRouteRoute
    }
    '/$realmId/manage/realms': {
      id: '/$realmId/manage/realms'
      path: '/realms'
      fullPath: '/$realmId/manage/realms'
      preLoaderRoute: typeof RealmIdManageRealmsRouteImport
      parentRoute: typeof RealmIdManageRouteRoute
    }
    '/$realmId/manage/products': {
      id: '/$realmId/manage/products'
      path: '/products'
      fullPath: '/$realmId/manage/products'
      preLoaderRoute: typeof RealmIdManageProductsRouteImport
      parentRoute: typeof RealmIdManageRouteRoute
    }
    '/$realmId/manage/points-packages': {
      id: '/$realmId/manage/points-packages'
      path: '/points-packages'
      fullPath: '/$realmId/manage/points-packages'
      preLoaderRoute: typeof RealmIdManagePointsPackagesRouteImport
      parentRoute: typeof RealmIdManageRouteRoute
    }
    '/$realmId/manage/points': {
      id: '/$realmId/manage/points'
      path: '/points'
      fullPath: '/$realmId/manage/points'
      preLoaderRoute: typeof RealmIdManagePointsRouteImport
      parentRoute: typeof RealmIdManageRouteRoute
    }
    '/$realmId/manage/permissions': {
      id: '/$realmId/manage/permissions'
      path: '/permissions'
      fullPath: '/$realmId/manage/permissions'
      preLoaderRoute: typeof RealmIdManagePermissionsRouteImport
      parentRoute: typeof RealmIdManageRouteRoute
    }
    '/$realmId/manage/client-apps': {
      id: '/$realmId/manage/client-apps'
      path: '/client-apps'
      fullPath: '/$realmId/manage/client-apps'
      preLoaderRoute: typeof RealmIdManageClientAppsRouteImport
      parentRoute: typeof RealmIdManageRouteRoute
    }
    '/$realmId/manage/billing': {
      id: '/$realmId/manage/billing'
      path: '/billing'
      fullPath: '/$realmId/manage/billing'
      preLoaderRoute: typeof RealmIdManageBillingRouteImport
      parentRoute: typeof RealmIdManageRouteRoute
    }
    '/$realmId/device/$userCode': {
      id: '/$realmId/device/$userCode'
      path: '/$userCode'
      fullPath: '/$realmId/device/$userCode'
      preLoaderRoute: typeof RealmIdDeviceUserCodeRouteImport
      parentRoute: typeof RealmIdDeviceRoute
    }
    '/$realmId/auth/verify-email': {
      id: '/$realmId/auth/verify-email'
      path: '/verify-email'
      fullPath: '/$realmId/auth/verify-email'
      preLoaderRoute: typeof RealmIdAuthVerifyEmailRouteImport
      parentRoute: typeof RealmIdAuthRouteRoute
    }
    '/$realmId/auth/register': {
      id: '/$realmId/auth/register'
      path: '/register'
      fullPath: '/$realmId/auth/register'
      preLoaderRoute: typeof RealmIdAuthRegisterRouteImport
      parentRoute: typeof RealmIdAuthRouteRoute
    }
    '/$realmId/auth/login': {
      id: '/$realmId/auth/login'
      path: '/login'
      fullPath: '/$realmId/auth/login'
      preLoaderRoute: typeof RealmIdAuthLoginRouteImport
      parentRoute: typeof RealmIdAuthRouteRoute
    }
    '/$realmId/user/security/': {
      id: '/$realmId/user/security/'
      path: '/'
      fullPath: '/$realmId/user/security/'
      preLoaderRoute: typeof RealmIdUserSecurityIndexRouteImport
      parentRoute: typeof RealmIdUserSecurityRoute
    }
    '/$realmId/manage/points-packages/': {
      id: '/$realmId/manage/points-packages/'
      path: '/'
      fullPath: '/$realmId/manage/points-packages/'
      preLoaderRoute: typeof RealmIdManagePointsPackagesIndexRouteImport
      parentRoute: typeof RealmIdManagePointsPackagesRoute
    }
    '/$realmId/manage/client-apps/': {
      id: '/$realmId/manage/client-apps/'
      path: '/'
      fullPath: '/$realmId/manage/client-apps/'
      preLoaderRoute: typeof RealmIdManageClientAppsIndexRouteImport
      parentRoute: typeof RealmIdManageClientAppsRoute
    }
    '/$realmId/manage/billing/': {
      id: '/$realmId/manage/billing/'
      path: '/'
      fullPath: '/$realmId/manage/billing/'
      preLoaderRoute: typeof RealmIdManageBillingIndexRouteImport
      parentRoute: typeof RealmIdManageBillingRoute
    }
    '/$realmId/manage/audit/': {
      id: '/$realmId/manage/audit/'
      path: '/audit'
      fullPath: '/$realmId/manage/audit/'
      preLoaderRoute: typeof RealmIdManageAuditIndexRouteImport
      parentRoute: typeof RealmIdManageRouteRoute
    }
    '/$realmId/user/security/totp-setup': {
      id: '/$realmId/user/security/totp-setup'
      path: '/totp-setup'
      fullPath: '/$realmId/user/security/totp-setup'
      preLoaderRoute: typeof RealmIdUserSecurityTotpSetupRouteImport
      parentRoute: typeof RealmIdUserSecurityRoute
    }
    '/$realmId/subscription/$subscriptionId/history': {
      id: '/$realmId/subscription/$subscriptionId/history'
      path: '/subscription/$subscriptionId/history'
      fullPath: '/$realmId/subscription/$subscriptionId/history'
      preLoaderRoute: typeof RealmIdSubscriptionSubscriptionIdHistoryRouteImport
      parentRoute: typeof RealmIdRouteRoute
    }
    '/$realmId/manage/points/realm-config': {
      id: '/$realmId/manage/points/realm-config'
      path: '/realm-config'
      fullPath: '/$realmId/manage/points/realm-config'
      preLoaderRoute: typeof RealmIdManagePointsRealmConfigRouteImport
      parentRoute: typeof RealmIdManagePointsRoute
    }
    '/$realmId/manage/points/free-stats': {
      id: '/$realmId/manage/points/free-stats'
      path: '/free-stats'
      fullPath: '/$realmId/manage/points/free-stats'
      preLoaderRoute: typeof RealmIdManagePointsFreeStatsRouteImport
      parentRoute: typeof RealmIdManagePointsRoute
    }
    '/$realmId/manage/points/configs': {
      id: '/$realmId/manage/points/configs'
      path: '/configs'
      fullPath: '/$realmId/manage/points/configs'
      preLoaderRoute: typeof RealmIdManagePointsConfigsRouteImport
      parentRoute: typeof RealmIdManagePointsRoute
    }
    '/$realmId/manage/points/accounts': {
      id: '/$realmId/manage/points/accounts'
      path: '/accounts'
      fullPath: '/$realmId/manage/points/accounts'
      preLoaderRoute: typeof RealmIdManagePointsAccountsRouteImport
      parentRoute: typeof RealmIdManagePointsRoute
    }
    '/$realmId/manage/points-packages/new': {
      id: '/$realmId/manage/points-packages/new'
      path: '/new'
      fullPath: '/$realmId/manage/points-packages/new'
      preLoaderRoute: typeof RealmIdManagePointsPackagesNewRouteImport
      parentRoute: typeof RealmIdManagePointsPackagesRoute
    }
    '/$realmId/manage/client-apps/new': {
      id: '/$realmId/manage/client-apps/new'
      path: '/new'
      fullPath: '/$realmId/manage/client-apps/new'
      preLoaderRoute: typeof RealmIdManageClientAppsNewRouteImport
      parentRoute: typeof RealmIdManageClientAppsRoute
    }
    '/$realmId/manage/billing/plans': {
      id: '/$realmId/manage/billing/plans'
      path: '/plans'
      fullPath: '/$realmId/manage/billing/plans'
      preLoaderRoute: typeof RealmIdManageBillingPlansRouteImport
      parentRoute: typeof RealmIdManageBillingRoute
    }
    '/$realmId/manage/billing/payment-providers': {
      id: '/$realmId/manage/billing/payment-providers'
      path: '/payment-providers'
      fullPath: '/$realmId/manage/billing/payment-providers'
      preLoaderRoute: typeof RealmIdManageBillingPaymentProvidersRouteImport
      parentRoute: typeof RealmIdManageBillingRoute
    }
    '/$realmId/manage/billing/invoices': {
      id: '/$realmId/manage/billing/invoices'
      path: '/invoices'
      fullPath: '/$realmId/manage/billing/invoices'
      preLoaderRoute: typeof RealmIdManageBillingInvoicesRouteImport
      parentRoute: typeof RealmIdManageBillingRoute
    }
    '/$realmId/manage/billing/invoices/': {
      id: '/$realmId/manage/billing/invoices/'
      path: '/'
      fullPath: '/$realmId/manage/billing/invoices/'
      preLoaderRoute: typeof RealmIdManageBillingInvoicesIndexRouteImport
      parentRoute: typeof RealmIdManageBillingInvoicesRoute
    }
    '/$realmId/manage/points-packages/$packageId/edit': {
      id: '/$realmId/manage/points-packages/$packageId/edit'
      path: '/$packageId/edit'
      fullPath: '/$realmId/manage/points-packages/$packageId/edit'
      preLoaderRoute: typeof RealmIdManagePointsPackagesPackageIdEditRouteImport
      parentRoute: typeof RealmIdManagePointsPackagesRoute
    }
    '/$realmId/manage/client-apps/$clientAppId/edit': {
      id: '/$realmId/manage/client-apps/$clientAppId/edit'
      path: '/$clientAppId/edit'
      fullPath: '/$realmId/manage/client-apps/$clientAppId/edit'
      preLoaderRoute: typeof RealmIdManageClientAppsClientAppIdEditRouteImport
      parentRoute: typeof RealmIdManageClientAppsRoute
    }
    '/$realmId/manage/billing/plans/new': {
      id: '/$realmId/manage/billing/plans/new'
      path: '/new'
      fullPath: '/$realmId/manage/billing/plans/new'
      preLoaderRoute: typeof RealmIdManageBillingPlansNewRouteImport
      parentRoute: typeof RealmIdManageBillingPlansRoute
    }
    '/$realmId/manage/billing/invoices/new': {
      id: '/$realmId/manage/billing/invoices/new'
      path: '/new'
      fullPath: '/$realmId/manage/billing/invoices/new'
      preLoaderRoute: typeof RealmIdManageBillingInvoicesNewRouteImport
      parentRoute: typeof RealmIdManageBillingInvoicesRoute
    }
    '/$realmId/manage/billing/plans/$planId/edit': {
      id: '/$realmId/manage/billing/plans/$planId/edit'
      path: '/$planId/edit'
      fullPath: '/$realmId/manage/billing/plans/$planId/edit'
      preLoaderRoute: typeof RealmIdManageBillingPlansPlanIdEditRouteImport
      parentRoute: typeof RealmIdManageBillingPlansRoute
    }
    '/$realmId/manage/billing/invoices/$invoiceId/edit': {
      id: '/$realmId/manage/billing/invoices/$invoiceId/edit'
      path: '/$invoiceId/edit'
      fullPath: '/$realmId/manage/billing/invoices/$invoiceId/edit'
      preLoaderRoute: typeof RealmIdManageBillingInvoicesInvoiceIdEditRouteImport
      parentRoute: typeof RealmIdManageBillingInvoicesRoute
    }
  }
}

interface RealmIdAuthRouteRouteChildren {
  RealmIdAuthLoginRoute: typeof RealmIdAuthLoginRoute
  RealmIdAuthRegisterRoute: typeof RealmIdAuthRegisterRoute
  RealmIdAuthVerifyEmailRoute: typeof RealmIdAuthVerifyEmailRoute
}

const RealmIdAuthRouteRouteChildren: RealmIdAuthRouteRouteChildren = {
  RealmIdAuthLoginRoute: RealmIdAuthLoginRoute,
  RealmIdAuthRegisterRoute: RealmIdAuthRegisterRoute,
  RealmIdAuthVerifyEmailRoute: RealmIdAuthVerifyEmailRoute,
}

const RealmIdAuthRouteRouteWithChildren =
  RealmIdAuthRouteRoute._addFileChildren(RealmIdAuthRouteRouteChildren)

interface RealmIdManageBillingInvoicesRouteChildren {
  RealmIdManageBillingInvoicesNewRoute: typeof RealmIdManageBillingInvoicesNewRoute
  RealmIdManageBillingInvoicesIndexRoute: typeof RealmIdManageBillingInvoicesIndexRoute
  RealmIdManageBillingInvoicesInvoiceIdEditRoute: typeof RealmIdManageBillingInvoicesInvoiceIdEditRoute
}

const RealmIdManageBillingInvoicesRouteChildren: RealmIdManageBillingInvoicesRouteChildren =
  {
    RealmIdManageBillingInvoicesNewRoute: RealmIdManageBillingInvoicesNewRoute,
    RealmIdManageBillingInvoicesIndexRoute:
      RealmIdManageBillingInvoicesIndexRoute,
    RealmIdManageBillingInvoicesInvoiceIdEditRoute:
      RealmIdManageBillingInvoicesInvoiceIdEditRoute,
  }

const RealmIdManageBillingInvoicesRouteWithChildren =
  RealmIdManageBillingInvoicesRoute._addFileChildren(
    RealmIdManageBillingInvoicesRouteChildren,
  )

interface RealmIdManageBillingPlansRouteChildren {
  RealmIdManageBillingPlansNewRoute: typeof RealmIdManageBillingPlansNewRoute
  RealmIdManageBillingPlansPlanIdEditRoute: typeof RealmIdManageBillingPlansPlanIdEditRoute
}

const RealmIdManageBillingPlansRouteChildren: RealmIdManageBillingPlansRouteChildren =
  {
    RealmIdManageBillingPlansNewRoute: RealmIdManageBillingPlansNewRoute,
    RealmIdManageBillingPlansPlanIdEditRoute:
      RealmIdManageBillingPlansPlanIdEditRoute,
  }

const RealmIdManageBillingPlansRouteWithChildren =
  RealmIdManageBillingPlansRoute._addFileChildren(
    RealmIdManageBillingPlansRouteChildren,
  )

interface RealmIdManageBillingRouteChildren {
  RealmIdManageBillingInvoicesRoute: typeof RealmIdManageBillingInvoicesRouteWithChildren
  RealmIdManageBillingPaymentProvidersRoute: typeof RealmIdManageBillingPaymentProvidersRoute
  RealmIdManageBillingPlansRoute: typeof RealmIdManageBillingPlansRouteWithChildren
  RealmIdManageBillingIndexRoute: typeof RealmIdManageBillingIndexRoute
}

const RealmIdManageBillingRouteChildren: RealmIdManageBillingRouteChildren = {
  RealmIdManageBillingInvoicesRoute:
    RealmIdManageBillingInvoicesRouteWithChildren,
  RealmIdManageBillingPaymentProvidersRoute:
    RealmIdManageBillingPaymentProvidersRoute,
  RealmIdManageBillingPlansRoute: RealmIdManageBillingPlansRouteWithChildren,
  RealmIdManageBillingIndexRoute: RealmIdManageBillingIndexRoute,
}

const RealmIdManageBillingRouteWithChildren =
  RealmIdManageBillingRoute._addFileChildren(RealmIdManageBillingRouteChildren)

interface RealmIdManageClientAppsRouteChildren {
  RealmIdManageClientAppsNewRoute: typeof RealmIdManageClientAppsNewRoute
  RealmIdManageClientAppsIndexRoute: typeof RealmIdManageClientAppsIndexRoute
  RealmIdManageClientAppsClientAppIdEditRoute: typeof RealmIdManageClientAppsClientAppIdEditRoute
}

const RealmIdManageClientAppsRouteChildren: RealmIdManageClientAppsRouteChildren =
  {
    RealmIdManageClientAppsNewRoute: RealmIdManageClientAppsNewRoute,
    RealmIdManageClientAppsIndexRoute: RealmIdManageClientAppsIndexRoute,
    RealmIdManageClientAppsClientAppIdEditRoute:
      RealmIdManageClientAppsClientAppIdEditRoute,
  }

const RealmIdManageClientAppsRouteWithChildren =
  RealmIdManageClientAppsRoute._addFileChildren(
    RealmIdManageClientAppsRouteChildren,
  )

interface RealmIdManagePointsRouteChildren {
  RealmIdManagePointsAccountsRoute: typeof RealmIdManagePointsAccountsRoute
  RealmIdManagePointsConfigsRoute: typeof RealmIdManagePointsConfigsRoute
  RealmIdManagePointsFreeStatsRoute: typeof RealmIdManagePointsFreeStatsRoute
  RealmIdManagePointsRealmConfigRoute: typeof RealmIdManagePointsRealmConfigRoute
}

const RealmIdManagePointsRouteChildren: RealmIdManagePointsRouteChildren = {
  RealmIdManagePointsAccountsRoute: RealmIdManagePointsAccountsRoute,
  RealmIdManagePointsConfigsRoute: RealmIdManagePointsConfigsRoute,
  RealmIdManagePointsFreeStatsRoute: RealmIdManagePointsFreeStatsRoute,
  RealmIdManagePointsRealmConfigRoute: RealmIdManagePointsRealmConfigRoute,
}

const RealmIdManagePointsRouteWithChildren =
  RealmIdManagePointsRoute._addFileChildren(RealmIdManagePointsRouteChildren)

interface RealmIdManagePointsPackagesRouteChildren {
  RealmIdManagePointsPackagesNewRoute: typeof RealmIdManagePointsPackagesNewRoute
  RealmIdManagePointsPackagesIndexRoute: typeof RealmIdManagePointsPackagesIndexRoute
  RealmIdManagePointsPackagesPackageIdEditRoute: typeof RealmIdManagePointsPackagesPackageIdEditRoute
}

const RealmIdManagePointsPackagesRouteChildren: RealmIdManagePointsPackagesRouteChildren =
  {
    RealmIdManagePointsPackagesNewRoute: RealmIdManagePointsPackagesNewRoute,
    RealmIdManagePointsPackagesIndexRoute:
      RealmIdManagePointsPackagesIndexRoute,
    RealmIdManagePointsPackagesPackageIdEditRoute:
      RealmIdManagePointsPackagesPackageIdEditRoute,
  }

const RealmIdManagePointsPackagesRouteWithChildren =
  RealmIdManagePointsPackagesRoute._addFileChildren(
    RealmIdManagePointsPackagesRouteChildren,
  )

interface RealmIdManageRouteRouteChildren {
  RealmIdManageBillingRoute: typeof RealmIdManageBillingRouteWithChildren
  RealmIdManageClientAppsRoute: typeof RealmIdManageClientAppsRouteWithChildren
  RealmIdManagePermissionsRoute: typeof RealmIdManagePermissionsRoute
  RealmIdManagePointsRoute: typeof RealmIdManagePointsRouteWithChildren
  RealmIdManagePointsPackagesRoute: typeof RealmIdManagePointsPackagesRouteWithChildren
  RealmIdManageProductsRoute: typeof RealmIdManageProductsRoute
  RealmIdManageRealmsRoute: typeof RealmIdManageRealmsRoute
  RealmIdManageRolesRoute: typeof RealmIdManageRolesRoute
  RealmIdManageSettingsRoute: typeof RealmIdManageSettingsRoute
  RealmIdManageSubscriptionRoute: typeof RealmIdManageSubscriptionRoute
  RealmIdManageSubscriptionHistoryRoute: typeof RealmIdManageSubscriptionHistoryRoute
  RealmIdManageUsersRoute: typeof RealmIdManageUsersRoute
  RealmIdManageIndexRoute: typeof RealmIdManageIndexRoute
  RealmIdManageAuditIndexRoute: typeof RealmIdManageAuditIndexRoute
}

const RealmIdManageRouteRouteChildren: RealmIdManageRouteRouteChildren = {
  RealmIdManageBillingRoute: RealmIdManageBillingRouteWithChildren,
  RealmIdManageClientAppsRoute: RealmIdManageClientAppsRouteWithChildren,
  RealmIdManagePermissionsRoute: RealmIdManagePermissionsRoute,
  RealmIdManagePointsRoute: RealmIdManagePointsRouteWithChildren,
  RealmIdManagePointsPackagesRoute:
    RealmIdManagePointsPackagesRouteWithChildren,
  RealmIdManageProductsRoute: RealmIdManageProductsRoute,
  RealmIdManageRealmsRoute: RealmIdManageRealmsRoute,
  RealmIdManageRolesRoute: RealmIdManageRolesRoute,
  RealmIdManageSettingsRoute: RealmIdManageSettingsRoute,
  RealmIdManageSubscriptionRoute: RealmIdManageSubscriptionRoute,
  RealmIdManageSubscriptionHistoryRoute: RealmIdManageSubscriptionHistoryRoute,
  RealmIdManageUsersRoute: RealmIdManageUsersRoute,
  RealmIdManageIndexRoute: RealmIdManageIndexRoute,
  RealmIdManageAuditIndexRoute: RealmIdManageAuditIndexRoute,
}

const RealmIdManageRouteRouteWithChildren =
  RealmIdManageRouteRoute._addFileChildren(RealmIdManageRouteRouteChildren)

interface RealmIdUserSecurityRouteChildren {
  RealmIdUserSecurityTotpSetupRoute: typeof RealmIdUserSecurityTotpSetupRoute
  RealmIdUserSecurityIndexRoute: typeof RealmIdUserSecurityIndexRoute
}

const RealmIdUserSecurityRouteChildren: RealmIdUserSecurityRouteChildren = {
  RealmIdUserSecurityTotpSetupRoute: RealmIdUserSecurityTotpSetupRoute,
  RealmIdUserSecurityIndexRoute: RealmIdUserSecurityIndexRoute,
}

const RealmIdUserSecurityRouteWithChildren =
  RealmIdUserSecurityRoute._addFileChildren(RealmIdUserSecurityRouteChildren)

interface RealmIdUserRouteRouteChildren {
  RealmIdUserInvoicesRoute: typeof RealmIdUserInvoicesRoute
  RealmIdUserPointsRoute: typeof RealmIdUserPointsRoute
  RealmIdUserProfileRoute: typeof RealmIdUserProfileRoute
  RealmIdUserPurchasePointsRoute: typeof RealmIdUserPurchasePointsRoute
  RealmIdUserSecurityRoute: typeof RealmIdUserSecurityRouteWithChildren
  RealmIdUserSubscriptionHistoryRoute: typeof RealmIdUserSubscriptionHistoryRoute
}

const RealmIdUserRouteRouteChildren: RealmIdUserRouteRouteChildren = {
  RealmIdUserInvoicesRoute: RealmIdUserInvoicesRoute,
  RealmIdUserPointsRoute: RealmIdUserPointsRoute,
  RealmIdUserProfileRoute: RealmIdUserProfileRoute,
  RealmIdUserPurchasePointsRoute: RealmIdUserPurchasePointsRoute,
  RealmIdUserSecurityRoute: RealmIdUserSecurityRouteWithChildren,
  RealmIdUserSubscriptionHistoryRoute: RealmIdUserSubscriptionHistoryRoute,
}

const RealmIdUserRouteRouteWithChildren =
  RealmIdUserRouteRoute._addFileChildren(RealmIdUserRouteRouteChildren)

interface RealmIdDeviceRouteChildren {
  RealmIdDeviceUserCodeRoute: typeof RealmIdDeviceUserCodeRoute
  RealmIdDeviceIndexRoute: typeof RealmIdDeviceIndexRoute
}

const RealmIdDeviceRouteChildren: RealmIdDeviceRouteChildren = {
  RealmIdDeviceUserCodeRoute: RealmIdDeviceUserCodeRoute,
  RealmIdDeviceIndexRoute: RealmIdDeviceIndexRoute,
}

const RealmIdDeviceRouteWithChildren = RealmIdDeviceRoute._addFileChildren(
  RealmIdDeviceRouteChildren,
)

interface RealmIdRouteRouteChildren {
  RealmIdAuthRouteRoute: typeof RealmIdAuthRouteRouteWithChildren
  RealmIdManageRouteRoute: typeof RealmIdManageRouteRouteWithChildren
  RealmIdUserRouteRoute: typeof RealmIdUserRouteRouteWithChildren
  RealmIdDeviceRoute: typeof RealmIdDeviceRouteWithChildren
  RealmIdSubscriptionMySubscriptionsRoute: typeof RealmIdSubscriptionMySubscriptionsRoute
  RealmIdSubscriptionSubscriptionIdHistoryRoute: typeof RealmIdSubscriptionSubscriptionIdHistoryRoute
}

const RealmIdRouteRouteChildren: RealmIdRouteRouteChildren = {
  RealmIdAuthRouteRoute: RealmIdAuthRouteRouteWithChildren,
  RealmIdManageRouteRoute: RealmIdManageRouteRouteWithChildren,
  RealmIdUserRouteRoute: RealmIdUserRouteRouteWithChildren,
  RealmIdDeviceRoute: RealmIdDeviceRouteWithChildren,
  RealmIdSubscriptionMySubscriptionsRoute:
    RealmIdSubscriptionMySubscriptionsRoute,
  RealmIdSubscriptionSubscriptionIdHistoryRoute:
    RealmIdSubscriptionSubscriptionIdHistoryRoute,
}

const RealmIdRouteRouteWithChildren = RealmIdRouteRoute._addFileChildren(
  RealmIdRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RealmIdRouteRoute: RealmIdRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
