/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RealmIdRouteRouteImport } from './routes/$realmId/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RealmIdDeviceRouteImport } from './routes/$realmId/device'
import { Route as RealmIdUserRouteRouteImport } from './routes/$realmId/user/route'
import { Route as RealmIdManageRouteRouteImport } from './routes/$realmId/manage/route'
import { Route as RealmIdLegalRouteRouteImport } from './routes/$realmId/legal/route'
import { Route as RealmIdAuthRouteRouteImport } from './routes/$realmId/auth/route'
import { Route as RealmIdManageIndexRouteImport } from './routes/$realmId/manage/index'
import { Route as RealmIdDeviceIndexRouteImport } from './routes/$realmId/device.index'
import { Route as RealmIdUserSubscriptionHistoryRouteImport } from './routes/$realmId/user/subscription-history'
import { Route as RealmIdUserSecurityRouteImport } from './routes/$realmId/user/security'
import { Route as RealmIdUserPurchasePointsRouteImport } from './routes/$realmId/user/purchase-points'
import { Route as RealmIdUserProfileRouteImport } from './routes/$realmId/user/profile'
import { Route as RealmIdUserPointsRouteImport } from './routes/$realmId/user/points'
import { Route as RealmIdUserInvoicesRouteImport } from './routes/$realmId/user/invoices'
import { Route as RealmIdSubscriptionMySubscriptionsRouteImport } from './routes/$realmId/subscription/my-subscriptions'
import { Route as RealmIdManageUsersRouteImport } from './routes/$realmId/manage/users'
import { Route as RealmIdManageSubscriptionHistoryRouteImport } from './routes/$realmId/manage/subscription-history'
import { Route as RealmIdManageSubscriptionRouteImport } from './routes/$realmId/manage/subscription'
import { Route as RealmIdManageSettingsRouteImport } from './routes/$realmId/manage/settings'
import { Route as RealmIdManageRolesRouteImport } from './routes/$realmId/manage/roles'
import { Route as RealmIdManageRealmsRouteImport } from './routes/$realmId/manage/realms'
import { Route as RealmIdManagePointsRouteImport } from './routes/$realmId/manage/points'
import { Route as RealmIdManagePermissionsRouteImport } from './routes/$realmId/manage/permissions'
import { Route as RealmIdManageClientAppsRouteImport } from './routes/$realmId/manage/client-apps'
import { Route as RealmIdManageBillingRouteImport } from './routes/$realmId/manage/billing'
import { Route as RealmIdManageApiKeysRouteImport } from './routes/$realmId/manage/api-keys'
import { Route as RealmIdLegalAgreementTypeRouteImport } from './routes/$realmId/legal/$agreementType'
import { Route as RealmIdDeviceUserCodeRouteImport } from './routes/$realmId/device.$userCode'
import { Route as RealmIdAuthVerifyEmailRouteImport } from './routes/$realmId/auth/verify-email'
import { Route as RealmIdAuthResetPasswordRouteImport } from './routes/$realmId/auth/reset-password'
import { Route as RealmIdAuthRegisterRouteImport } from './routes/$realmId/auth/register'
import { Route as RealmIdAuthLoginRouteImport } from './routes/$realmId/auth/login'
import { Route as RealmIdAuthForgotPasswordRouteImport } from './routes/$realmId/auth/forgot-password'
import { Route as RealmIdUserSecurityIndexRouteImport } from './routes/$realmId/user/security/index'
import { Route as RealmIdUserInvoicesIndexRouteImport } from './routes/$realmId/user/invoices/index'
import { Route as RealmIdManageClientAppsIndexRouteImport } from './routes/$realmId/manage/client-apps/index'
import { Route as RealmIdManageAuditIndexRouteImport } from './routes/$realmId/manage/audit/index'
import { Route as RealmIdManageApiKeysIndexRouteImport } from './routes/$realmId/manage/api-keys/index'
import { Route as RealmIdUserSecurityTotpSetupRouteImport } from './routes/$realmId/user/security/totp-setup'
import { Route as RealmIdUserInvoicesNewRouteImport } from './routes/$realmId/user/invoices/new'
import { Route as RealmIdSubscriptionSubscriptionIdHistoryRouteImport } from './routes/$realmId/subscription/$subscriptionId/history'
import { Route as RealmIdManagePointsWalletsRouteImport } from './routes/$realmId/manage/points/wallets'
import { Route as RealmIdManagePointsDefaultConfigRouteImport } from './routes/$realmId/manage/points/default-config'
import { Route as RealmIdManageClientAppsNewRouteImport } from './routes/$realmId/manage/client-apps/new'
import { Route as RealmIdManageBillingSubscriptionsRouteImport } from './routes/$realmId/manage/billing/subscriptions'
import { Route as RealmIdManageBillingPaymentProvidersRouteImport } from './routes/$realmId/manage/billing/payment-providers'
import { Route as RealmIdManageBillingInvoicesRouteImport } from './routes/$realmId/manage/billing/invoices'
import { Route as RealmIdManageBillingEntitlementMappingsRouteImport } from './routes/$realmId/manage/billing/entitlement-mappings'
import { Route as RealmIdManageBillingCreditBucketsRouteImport } from './routes/$realmId/manage/billing/credit-buckets'
import { Route as RealmIdManageApiKeysRevealRouteImport } from './routes/$realmId/manage/api-keys/reveal'
import { Route as RealmIdManageApiKeysNewRouteImport } from './routes/$realmId/manage/api-keys/new'
import { Route as RealmIdManageBillingPaymentProvidersIndexRouteImport } from './routes/$realmId/manage/billing/payment-providers/index'
import { Route as RealmIdManageBillingInvoicesIndexRouteImport } from './routes/$realmId/manage/billing/invoices/index'
import { Route as RealmIdManageBillingCreditBucketsIndexRouteImport } from './routes/$realmId/manage/billing/credit-buckets/index'
import { Route as RealmIdManageClientAppsClientAppIdEditRouteImport } from './routes/$realmId/manage/client-apps/$clientAppId.edit'
import { Route as RealmIdManageBillingPaymentProvidersStripeRouteImport } from './routes/$realmId/manage/billing/payment-providers/stripe'
import { Route as RealmIdManageBillingPaymentProvidersCreemRouteImport } from './routes/$realmId/manage/billing/payment-providers/creem'
import { Route as RealmIdManageBillingInvoicesNewRouteImport } from './routes/$realmId/manage/billing/invoices/new'
import { Route as RealmIdManageBillingCreditBucketsOverviewRouteImport } from './routes/$realmId/manage/billing/credit-buckets/overview'
import { Route as RealmIdManageApiKeysApiKeyIdEditRouteImport } from './routes/$realmId/manage/api-keys/$apiKeyId.edit'
import { Route as RealmIdManageBillingInvoicesInvoiceIdEditRouteImport } from './routes/$realmId/manage/billing/invoices/$invoiceId.edit'

const RealmIdRouteRoute = RealmIdRouteRouteImport.update({
  id: '/$realmId',
  path: '/$realmId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RealmIdDeviceRoute = RealmIdDeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => RealmIdRouteRoute,
} as any)
const RealmIdUserRouteRoute = RealmIdUserRouteRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => RealmIdRouteRoute,
} as any)
const RealmIdManageRouteRoute = RealmIdManageRouteRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => RealmIdRouteRoute,
} as any)
const RealmIdLegalRouteRoute = RealmIdLegalRouteRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => RealmIdRouteRoute,
} as any)
const RealmIdAuthRouteRoute = RealmIdAuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => RealmIdRouteRoute,
} as any)
const RealmIdManageIndexRoute = RealmIdManageIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RealmIdManageRouteRoute,
} as any)
const RealmIdDeviceIndexRoute = RealmIdDeviceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RealmIdDeviceRoute,
} as any)
const RealmIdUserSubscriptionHistoryRoute =
  RealmIdUserSubscriptionHistoryRouteImport.update({
    id: '/subscription-history',
    path: '/subscription-history',
    getParentRoute: () => RealmIdUserRouteRoute,
  } as any)
const RealmIdUserSecurityRoute = RealmIdUserSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => RealmIdUserRouteRoute,
} as any)
const RealmIdUserPurchasePointsRoute =
  RealmIdUserPurchasePointsRouteImport.update({
    id: '/purchase-points',
    path: '/purchase-points',
    getParentRoute: () => RealmIdUserRouteRoute,
  } as any)
const RealmIdUserProfileRoute = RealmIdUserProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => RealmIdUserRouteRoute,
} as any)
const RealmIdUserPointsRoute = RealmIdUserPointsRouteImport.update({
  id: '/points',
  path: '/points',
  getParentRoute: () => RealmIdUserRouteRoute,
} as any)
const RealmIdUserInvoicesRoute = RealmIdUserInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => RealmIdUserRouteRoute,
} as any)
const RealmIdSubscriptionMySubscriptionsRoute =
  RealmIdSubscriptionMySubscriptionsRouteImport.update({
    id: '/subscription/my-subscriptions',
    path: '/subscription/my-subscriptions',
    getParentRoute: () => RealmIdRouteRoute,
  } as any)
const RealmIdManageUsersRoute = RealmIdManageUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => RealmIdManageRouteRoute,
} as any)
const RealmIdManageSubscriptionHistoryRoute =
  RealmIdManageSubscriptionHistoryRouteImport.update({
    id: '/subscription-history',
    path: '/subscription-history',
    getParentRoute: () => RealmIdManageRouteRoute,
  } as any)
const RealmIdManageSubscriptionRoute =
  RealmIdManageSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => RealmIdManageRouteRoute,
  } as any)
const RealmIdManageSettingsRoute = RealmIdManageSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => RealmIdManageRouteRoute,
} as any)
const RealmIdManageRolesRoute = RealmIdManageRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => RealmIdManageRouteRoute,
} as any)
const RealmIdManageRealmsRoute = RealmIdManageRealmsRouteImport.update({
  id: '/realms',
  path: '/realms',
  getParentRoute: () => RealmIdManageRouteRoute,
} as any)
const RealmIdManagePointsRoute = RealmIdManagePointsRouteImport.update({
  id: '/points',
  path: '/points',
  getParentRoute: () => RealmIdManageRouteRoute,
} as any)
const RealmIdManagePermissionsRoute =
  RealmIdManagePermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => RealmIdManageRouteRoute,
  } as any)
const RealmIdManageClientAppsRoute = RealmIdManageClientAppsRouteImport.update({
  id: '/client-apps',
  path: '/client-apps',
  getParentRoute: () => RealmIdManageRouteRoute,
} as any)
const RealmIdManageBillingRoute = RealmIdManageBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => RealmIdManageRouteRoute,
} as any)
const RealmIdManageApiKeysRoute = RealmIdManageApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => RealmIdManageRouteRoute,
} as any)
const RealmIdLegalAgreementTypeRoute =
  RealmIdLegalAgreementTypeRouteImport.update({
    id: '/$agreementType',
    path: '/$agreementType',
    getParentRoute: () => RealmIdLegalRouteRoute,
  } as any)
const RealmIdDeviceUserCodeRoute = RealmIdDeviceUserCodeRouteImport.update({
  id: '/$userCode',
  path: '/$userCode',
  getParentRoute: () => RealmIdDeviceRoute,
} as any)
const RealmIdAuthVerifyEmailRoute = RealmIdAuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => RealmIdAuthRouteRoute,
} as any)
const RealmIdAuthResetPasswordRoute =
  RealmIdAuthResetPasswordRouteImport.update({
    id: '/reset-password',
    path: '/reset-password',
    getParentRoute: () => RealmIdAuthRouteRoute,
  } as any)
const RealmIdAuthRegisterRoute = RealmIdAuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => RealmIdAuthRouteRoute,
} as any)
const RealmIdAuthLoginRoute = RealmIdAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => RealmIdAuthRouteRoute,
} as any)
const RealmIdAuthForgotPasswordRoute =
  RealmIdAuthForgotPasswordRouteImport.update({
    id: '/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => RealmIdAuthRouteRoute,
  } as any)
const RealmIdUserSecurityIndexRoute =
  RealmIdUserSecurityIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => RealmIdUserSecurityRoute,
  } as any)
const RealmIdUserInvoicesIndexRoute =
  RealmIdUserInvoicesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => RealmIdUserInvoicesRoute,
  } as any)
const RealmIdManageClientAppsIndexRoute =
  RealmIdManageClientAppsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => RealmIdManageClientAppsRoute,
  } as any)
const RealmIdManageAuditIndexRoute = RealmIdManageAuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => RealmIdManageRouteRoute,
} as any)
const RealmIdManageApiKeysIndexRoute =
  RealmIdManageApiKeysIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => RealmIdManageApiKeysRoute,
  } as any)
const RealmIdUserSecurityTotpSetupRoute =
  RealmIdUserSecurityTotpSetupRouteImport.update({
    id: '/totp-setup',
    path: '/totp-setup',
    getParentRoute: () => RealmIdUserSecurityRoute,
  } as any)
const RealmIdUserInvoicesNewRoute = RealmIdUserInvoicesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => RealmIdUserInvoicesRoute,
} as any)
const RealmIdSubscriptionSubscriptionIdHistoryRoute =
  RealmIdSubscriptionSubscriptionIdHistoryRouteImport.update({
    id: '/subscription/$subscriptionId/history',
    path: '/subscription/$subscriptionId/history',
    getParentRoute: () => RealmIdRouteRoute,
  } as any)
const RealmIdManagePointsWalletsRoute =
  RealmIdManagePointsWalletsRouteImport.update({
    id: '/wallets',
    path: '/wallets',
    getParentRoute: () => RealmIdManagePointsRoute,
  } as any)
const RealmIdManagePointsDefaultConfigRoute =
  RealmIdManagePointsDefaultConfigRouteImport.update({
    id: '/default-config',
    path: '/default-config',
    getParentRoute: () => RealmIdManagePointsRoute,
  } as any)
const RealmIdManageClientAppsNewRoute =
  RealmIdManageClientAppsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => RealmIdManageClientAppsRoute,
  } as any)
const RealmIdManageBillingSubscriptionsRoute =
  RealmIdManageBillingSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => RealmIdManageBillingRoute,
  } as any)
const RealmIdManageBillingPaymentProvidersRoute =
  RealmIdManageBillingPaymentProvidersRouteImport.update({
    id: '/payment-providers',
    path: '/payment-providers',
    getParentRoute: () => RealmIdManageBillingRoute,
  } as any)
const RealmIdManageBillingInvoicesRoute =
  RealmIdManageBillingInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => RealmIdManageBillingRoute,
  } as any)
const RealmIdManageBillingEntitlementMappingsRoute =
  RealmIdManageBillingEntitlementMappingsRouteImport.update({
    id: '/entitlement-mappings',
    path: '/entitlement-mappings',
    getParentRoute: () => RealmIdManageBillingRoute,
  } as any)
const RealmIdManageBillingCreditBucketsRoute =
  RealmIdManageBillingCreditBucketsRouteImport.update({
    id: '/credit-buckets',
    path: '/credit-buckets',
    getParentRoute: () => RealmIdManageBillingRoute,
  } as any)
const RealmIdManageApiKeysRevealRoute =
  RealmIdManageApiKeysRevealRouteImport.update({
    id: '/reveal',
    path: '/reveal',
    getParentRoute: () => RealmIdManageApiKeysRoute,
  } as any)
const RealmIdManageApiKeysNewRoute = RealmIdManageApiKeysNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => RealmIdManageApiKeysRoute,
} as any)
const RealmIdManageBillingPaymentProvidersIndexRoute =
  RealmIdManageBillingPaymentProvidersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => RealmIdManageBillingPaymentProvidersRoute,
  } as any)
const RealmIdManageBillingInvoicesIndexRoute =
  RealmIdManageBillingInvoicesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => RealmIdManageBillingInvoicesRoute,
  } as any)
const RealmIdManageBillingCreditBucketsIndexRoute =
  RealmIdManageBillingCreditBucketsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => RealmIdManageBillingCreditBucketsRoute,
  } as any)
const RealmIdManageClientAppsClientAppIdEditRoute =
  RealmIdManageClientAppsClientAppIdEditRouteImport.update({
    id: '/$clientAppId/edit',
    path: '/$clientAppId/edit',
    getParentRoute: () => RealmIdManageClientAppsRoute,
  } as any)
const RealmIdManageBillingPaymentProvidersStripeRoute =
  RealmIdManageBillingPaymentProvidersStripeRouteImport.update({
    id: '/stripe',
    path: '/stripe',
    getParentRoute: () => RealmIdManageBillingPaymentProvidersRoute,
  } as any)
const RealmIdManageBillingPaymentProvidersCreemRoute =
  RealmIdManageBillingPaymentProvidersCreemRouteImport.update({
    id: '/creem',
    path: '/creem',
    getParentRoute: () => RealmIdManageBillingPaymentProvidersRoute,
  } as any)
const RealmIdManageBillingInvoicesNewRoute =
  RealmIdManageBillingInvoicesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => RealmIdManageBillingInvoicesRoute,
  } as any)
const RealmIdManageBillingCreditBucketsOverviewRoute =
  RealmIdManageBillingCreditBucketsOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => RealmIdManageBillingCreditBucketsRoute,
  } as any)
const RealmIdManageApiKeysApiKeyIdEditRoute =
  RealmIdManageApiKeysApiKeyIdEditRouteImport.update({
    id: '/$apiKeyId/edit',
    path: '/$apiKeyId/edit',
    getParentRoute: () => RealmIdManageApiKeysRoute,
  } as any)
const RealmIdManageBillingInvoicesInvoiceIdEditRoute =
  RealmIdManageBillingInvoicesInvoiceIdEditRouteImport.update({
    id: '/$invoiceId/edit',
    path: '/$invoiceId/edit',
    getParentRoute: () => RealmIdManageBillingInvoicesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$realmId': typeof RealmIdRouteRouteWithChildren
  '/$realmId/auth': typeof RealmIdAuthRouteRouteWithChildren
  '/$realmId/legal': typeof RealmIdLegalRouteRouteWithChildren
  '/$realmId/manage': typeof RealmIdManageRouteRouteWithChildren
  '/$realmId/user': typeof RealmIdUserRouteRouteWithChildren
  '/$realmId/device': typeof RealmIdDeviceRouteWithChildren
  '/$realmId/auth/forgot-password': typeof RealmIdAuthForgotPasswordRoute
  '/$realmId/auth/login': typeof RealmIdAuthLoginRoute
  '/$realmId/auth/register': typeof RealmIdAuthRegisterRoute
  '/$realmId/auth/reset-password': typeof RealmIdAuthResetPasswordRoute
  '/$realmId/auth/verify-email': typeof RealmIdAuthVerifyEmailRoute
  '/$realmId/device/$userCode': typeof RealmIdDeviceUserCodeRoute
  '/$realmId/legal/$agreementType': typeof RealmIdLegalAgreementTypeRoute
  '/$realmId/manage/api-keys': typeof RealmIdManageApiKeysRouteWithChildren
  '/$realmId/manage/billing': typeof RealmIdManageBillingRouteWithChildren
  '/$realmId/manage/client-apps': typeof RealmIdManageClientAppsRouteWithChildren
  '/$realmId/manage/permissions': typeof RealmIdManagePermissionsRoute
  '/$realmId/manage/points': typeof RealmIdManagePointsRouteWithChildren
  '/$realmId/manage/realms': typeof RealmIdManageRealmsRoute
  '/$realmId/manage/roles': typeof RealmIdManageRolesRoute
  '/$realmId/manage/settings': typeof RealmIdManageSettingsRoute
  '/$realmId/manage/subscription': typeof RealmIdManageSubscriptionRoute
  '/$realmId/manage/subscription-history': typeof RealmIdManageSubscriptionHistoryRoute
  '/$realmId/manage/users': typeof RealmIdManageUsersRoute
  '/$realmId/subscription/my-subscriptions': typeof RealmIdSubscriptionMySubscriptionsRoute
  '/$realmId/user/invoices': typeof RealmIdUserInvoicesRouteWithChildren
  '/$realmId/user/points': typeof RealmIdUserPointsRoute
  '/$realmId/user/profile': typeof RealmIdUserProfileRoute
  '/$realmId/user/purchase-points': typeof RealmIdUserPurchasePointsRoute
  '/$realmId/user/security': typeof RealmIdUserSecurityRouteWithChildren
  '/$realmId/user/subscription-history': typeof RealmIdUserSubscriptionHistoryRoute
  '/$realmId/device/': typeof RealmIdDeviceIndexRoute
  '/$realmId/manage/': typeof RealmIdManageIndexRoute
  '/$realmId/manage/api-keys/new': typeof RealmIdManageApiKeysNewRoute
  '/$realmId/manage/api-keys/reveal': typeof RealmIdManageApiKeysRevealRoute
  '/$realmId/manage/billing/credit-buckets': typeof RealmIdManageBillingCreditBucketsRouteWithChildren
  '/$realmId/manage/billing/entitlement-mappings': typeof RealmIdManageBillingEntitlementMappingsRoute
  '/$realmId/manage/billing/invoices': typeof RealmIdManageBillingInvoicesRouteWithChildren
  '/$realmId/manage/billing/payment-providers': typeof RealmIdManageBillingPaymentProvidersRouteWithChildren
  '/$realmId/manage/billing/subscriptions': typeof RealmIdManageBillingSubscriptionsRoute
  '/$realmId/manage/client-apps/new': typeof RealmIdManageClientAppsNewRoute
  '/$realmId/manage/points/default-config': typeof RealmIdManagePointsDefaultConfigRoute
  '/$realmId/manage/points/wallets': typeof RealmIdManagePointsWalletsRoute
  '/$realmId/subscription/$subscriptionId/history': typeof RealmIdSubscriptionSubscriptionIdHistoryRoute
  '/$realmId/user/invoices/new': typeof RealmIdUserInvoicesNewRoute
  '/$realmId/user/security/totp-setup': typeof RealmIdUserSecurityTotpSetupRoute
  '/$realmId/manage/api-keys/': typeof RealmIdManageApiKeysIndexRoute
  '/$realmId/manage/audit/': typeof RealmIdManageAuditIndexRoute
  '/$realmId/manage/client-apps/': typeof RealmIdManageClientAppsIndexRoute
  '/$realmId/user/invoices/': typeof RealmIdUserInvoicesIndexRoute
  '/$realmId/user/security/': typeof RealmIdUserSecurityIndexRoute
  '/$realmId/manage/api-keys/$apiKeyId/edit': typeof RealmIdManageApiKeysApiKeyIdEditRoute
  '/$realmId/manage/billing/credit-buckets/overview': typeof RealmIdManageBillingCreditBucketsOverviewRoute
  '/$realmId/manage/billing/invoices/new': typeof RealmIdManageBillingInvoicesNewRoute
  '/$realmId/manage/billing/payment-providers/creem': typeof RealmIdManageBillingPaymentProvidersCreemRoute
  '/$realmId/manage/billing/payment-providers/stripe': typeof RealmIdManageBillingPaymentProvidersStripeRoute
  '/$realmId/manage/client-apps/$clientAppId/edit': typeof RealmIdManageClientAppsClientAppIdEditRoute
  '/$realmId/manage/billing/credit-buckets/': typeof RealmIdManageBillingCreditBucketsIndexRoute
  '/$realmId/manage/billing/invoices/': typeof RealmIdManageBillingInvoicesIndexRoute
  '/$realmId/manage/billing/payment-providers/': typeof RealmIdManageBillingPaymentProvidersIndexRoute
  '/$realmId/manage/billing/invoices/$invoiceId/edit': typeof RealmIdManageBillingInvoicesInvoiceIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$realmId': typeof RealmIdRouteRouteWithChildren
  '/$realmId/auth': typeof RealmIdAuthRouteRouteWithChildren
  '/$realmId/legal': typeof RealmIdLegalRouteRouteWithChildren
  '/$realmId/user': typeof RealmIdUserRouteRouteWithChildren
  '/$realmId/auth/forgot-password': typeof RealmIdAuthForgotPasswordRoute
  '/$realmId/auth/login': typeof RealmIdAuthLoginRoute
  '/$realmId/auth/register': typeof RealmIdAuthRegisterRoute
  '/$realmId/auth/reset-password': typeof RealmIdAuthResetPasswordRoute
  '/$realmId/auth/verify-email': typeof RealmIdAuthVerifyEmailRoute
  '/$realmId/device/$userCode': typeof RealmIdDeviceUserCodeRoute
  '/$realmId/legal/$agreementType': typeof RealmIdLegalAgreementTypeRoute
  '/$realmId/manage/billing': typeof RealmIdManageBillingRouteWithChildren
  '/$realmId/manage/permissions': typeof RealmIdManagePermissionsRoute
  '/$realmId/manage/points': typeof RealmIdManagePointsRouteWithChildren
  '/$realmId/manage/realms': typeof RealmIdManageRealmsRoute
  '/$realmId/manage/roles': typeof RealmIdManageRolesRoute
  '/$realmId/manage/settings': typeof RealmIdManageSettingsRoute
  '/$realmId/manage/subscription': typeof RealmIdManageSubscriptionRoute
  '/$realmId/manage/subscription-history': typeof RealmIdManageSubscriptionHistoryRoute
  '/$realmId/manage/users': typeof RealmIdManageUsersRoute
  '/$realmId/subscription/my-subscriptions': typeof RealmIdSubscriptionMySubscriptionsRoute
  '/$realmId/user/points': typeof RealmIdUserPointsRoute
  '/$realmId/user/profile': typeof RealmIdUserProfileRoute
  '/$realmId/user/purchase-points': typeof RealmIdUserPurchasePointsRoute
  '/$realmId/user/subscription-history': typeof RealmIdUserSubscriptionHistoryRoute
  '/$realmId/device': typeof RealmIdDeviceIndexRoute
  '/$realmId/manage': typeof RealmIdManageIndexRoute
  '/$realmId/manage/api-keys/new': typeof RealmIdManageApiKeysNewRoute
  '/$realmId/manage/api-keys/reveal': typeof RealmIdManageApiKeysRevealRoute
  '/$realmId/manage/billing/entitlement-mappings': typeof RealmIdManageBillingEntitlementMappingsRoute
  '/$realmId/manage/billing/subscriptions': typeof RealmIdManageBillingSubscriptionsRoute
  '/$realmId/manage/client-apps/new': typeof RealmIdManageClientAppsNewRoute
  '/$realmId/manage/points/default-config': typeof RealmIdManagePointsDefaultConfigRoute
  '/$realmId/manage/points/wallets': typeof RealmIdManagePointsWalletsRoute
  '/$realmId/subscription/$subscriptionId/history': typeof RealmIdSubscriptionSubscriptionIdHistoryRoute
  '/$realmId/user/invoices/new': typeof RealmIdUserInvoicesNewRoute
  '/$realmId/user/security/totp-setup': typeof RealmIdUserSecurityTotpSetupRoute
  '/$realmId/manage/api-keys': typeof RealmIdManageApiKeysIndexRoute
  '/$realmId/manage/audit': typeof RealmIdManageAuditIndexRoute
  '/$realmId/manage/client-apps': typeof RealmIdManageClientAppsIndexRoute
  '/$realmId/user/invoices': typeof RealmIdUserInvoicesIndexRoute
  '/$realmId/user/security': typeof RealmIdUserSecurityIndexRoute
  '/$realmId/manage/api-keys/$apiKeyId/edit': typeof RealmIdManageApiKeysApiKeyIdEditRoute
  '/$realmId/manage/billing/credit-buckets/overview': typeof RealmIdManageBillingCreditBucketsOverviewRoute
  '/$realmId/manage/billing/invoices/new': typeof RealmIdManageBillingInvoicesNewRoute
  '/$realmId/manage/billing/payment-providers/creem': typeof RealmIdManageBillingPaymentProvidersCreemRoute
  '/$realmId/manage/billing/payment-providers/stripe': typeof RealmIdManageBillingPaymentProvidersStripeRoute
  '/$realmId/manage/client-apps/$clientAppId/edit': typeof RealmIdManageClientAppsClientAppIdEditRoute
  '/$realmId/manage/billing/credit-buckets': typeof RealmIdManageBillingCreditBucketsIndexRoute
  '/$realmId/manage/billing/invoices': typeof RealmIdManageBillingInvoicesIndexRoute
  '/$realmId/manage/billing/payment-providers': typeof RealmIdManageBillingPaymentProvidersIndexRoute
  '/$realmId/manage/billing/invoices/$invoiceId/edit': typeof RealmIdManageBillingInvoicesInvoiceIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$realmId': typeof RealmIdRouteRouteWithChildren
  '/$realmId/auth': typeof RealmIdAuthRouteRouteWithChildren
  '/$realmId/legal': typeof RealmIdLegalRouteRouteWithChildren
  '/$realmId/manage': typeof RealmIdManageRouteRouteWithChildren
  '/$realmId/user': typeof RealmIdUserRouteRouteWithChildren
  '/$realmId/device': typeof RealmIdDeviceRouteWithChildren
  '/$realmId/auth/forgot-password': typeof RealmIdAuthForgotPasswordRoute
  '/$realmId/auth/login': typeof RealmIdAuthLoginRoute
  '/$realmId/auth/register': typeof RealmIdAuthRegisterRoute
  '/$realmId/auth/reset-password': typeof RealmIdAuthResetPasswordRoute
  '/$realmId/auth/verify-email': typeof RealmIdAuthVerifyEmailRoute
  '/$realmId/device/$userCode': typeof RealmIdDeviceUserCodeRoute
  '/$realmId/legal/$agreementType': typeof RealmIdLegalAgreementTypeRoute
  '/$realmId/manage/api-keys': typeof RealmIdManageApiKeysRouteWithChildren
  '/$realmId/manage/billing': typeof RealmIdManageBillingRouteWithChildren
  '/$realmId/manage/client-apps': typeof RealmIdManageClientAppsRouteWithChildren
  '/$realmId/manage/permissions': typeof RealmIdManagePermissionsRoute
  '/$realmId/manage/points': typeof RealmIdManagePointsRouteWithChildren
  '/$realmId/manage/realms': typeof RealmIdManageRealmsRoute
  '/$realmId/manage/roles': typeof RealmIdManageRolesRoute
  '/$realmId/manage/settings': typeof RealmIdManageSettingsRoute
  '/$realmId/manage/subscription': typeof RealmIdManageSubscriptionRoute
  '/$realmId/manage/subscription-history': typeof RealmIdManageSubscriptionHistoryRoute
  '/$realmId/manage/users': typeof RealmIdManageUsersRoute
  '/$realmId/subscription/my-subscriptions': typeof RealmIdSubscriptionMySubscriptionsRoute
  '/$realmId/user/invoices': typeof RealmIdUserInvoicesRouteWithChildren
  '/$realmId/user/points': typeof RealmIdUserPointsRoute
  '/$realmId/user/profile': typeof RealmIdUserProfileRoute
  '/$realmId/user/purchase-points': typeof RealmIdUserPurchasePointsRoute
  '/$realmId/user/security': typeof RealmIdUserSecurityRouteWithChildren
  '/$realmId/user/subscription-history': typeof RealmIdUserSubscriptionHistoryRoute
  '/$realmId/device/': typeof RealmIdDeviceIndexRoute
  '/$realmId/manage/': typeof RealmIdManageIndexRoute
  '/$realmId/manage/api-keys/new': typeof RealmIdManageApiKeysNewRoute
  '/$realmId/manage/api-keys/reveal': typeof RealmIdManageApiKeysRevealRoute
  '/$realmId/manage/billing/credit-buckets': typeof RealmIdManageBillingCreditBucketsRouteWithChildren
  '/$realmId/manage/billing/entitlement-mappings': typeof RealmIdManageBillingEntitlementMappingsRoute
  '/$realmId/manage/billing/invoices': typeof RealmIdManageBillingInvoicesRouteWithChildren
  '/$realmId/manage/billing/payment-providers': typeof RealmIdManageBillingPaymentProvidersRouteWithChildren
  '/$realmId/manage/billing/subscriptions': typeof RealmIdManageBillingSubscriptionsRoute
  '/$realmId/manage/client-apps/new': typeof RealmIdManageClientAppsNewRoute
  '/$realmId/manage/points/default-config': typeof RealmIdManagePointsDefaultConfigRoute
  '/$realmId/manage/points/wallets': typeof RealmIdManagePointsWalletsRoute
  '/$realmId/subscription/$subscriptionId/history': typeof RealmIdSubscriptionSubscriptionIdHistoryRoute
  '/$realmId/user/invoices/new': typeof RealmIdUserInvoicesNewRoute
  '/$realmId/user/security/totp-setup': typeof RealmIdUserSecurityTotpSetupRoute
  '/$realmId/manage/api-keys/': typeof RealmIdManageApiKeysIndexRoute
  '/$realmId/manage/audit/': typeof RealmIdManageAuditIndexRoute
  '/$realmId/manage/client-apps/': typeof RealmIdManageClientAppsIndexRoute
  '/$realmId/user/invoices/': typeof RealmIdUserInvoicesIndexRoute
  '/$realmId/user/security/': typeof RealmIdUserSecurityIndexRoute
  '/$realmId/manage/api-keys/$apiKeyId/edit': typeof RealmIdManageApiKeysApiKeyIdEditRoute
  '/$realmId/manage/billing/credit-buckets/overview': typeof RealmIdManageBillingCreditBucketsOverviewRoute
  '/$realmId/manage/billing/invoices/new': typeof RealmIdManageBillingInvoicesNewRoute
  '/$realmId/manage/billing/payment-providers/creem': typeof RealmIdManageBillingPaymentProvidersCreemRoute
  '/$realmId/manage/billing/payment-providers/stripe': typeof RealmIdManageBillingPaymentProvidersStripeRoute
  '/$realmId/manage/client-apps/$clientAppId/edit': typeof RealmIdManageClientAppsClientAppIdEditRoute
  '/$realmId/manage/billing/credit-buckets/': typeof RealmIdManageBillingCreditBucketsIndexRoute
  '/$realmId/manage/billing/invoices/': typeof RealmIdManageBillingInvoicesIndexRoute
  '/$realmId/manage/billing/payment-providers/': typeof RealmIdManageBillingPaymentProvidersIndexRoute
  '/$realmId/manage/billing/invoices/$invoiceId/edit': typeof RealmIdManageBillingInvoicesInvoiceIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$realmId'
    | '/$realmId/auth'
    | '/$realmId/legal'
    | '/$realmId/manage'
    | '/$realmId/user'
    | '/$realmId/device'
    | '/$realmId/auth/forgot-password'
    | '/$realmId/auth/login'
    | '/$realmId/auth/register'
    | '/$realmId/auth/reset-password'
    | '/$realmId/auth/verify-email'
    | '/$realmId/device/$userCode'
    | '/$realmId/legal/$agreementType'
    | '/$realmId/manage/api-keys'
    | '/$realmId/manage/billing'
    | '/$realmId/manage/client-apps'
    | '/$realmId/manage/permissions'
    | '/$realmId/manage/points'
    | '/$realmId/manage/realms'
    | '/$realmId/manage/roles'
    | '/$realmId/manage/settings'
    | '/$realmId/manage/subscription'
    | '/$realmId/manage/subscription-history'
    | '/$realmId/manage/users'
    | '/$realmId/subscription/my-subscriptions'
    | '/$realmId/user/invoices'
    | '/$realmId/user/points'
    | '/$realmId/user/profile'
    | '/$realmId/user/purchase-points'
    | '/$realmId/user/security'
    | '/$realmId/user/subscription-history'
    | '/$realmId/device/'
    | '/$realmId/manage/'
    | '/$realmId/manage/api-keys/new'
    | '/$realmId/manage/api-keys/reveal'
    | '/$realmId/manage/billing/credit-buckets'
    | '/$realmId/manage/billing/entitlement-mappings'
    | '/$realmId/manage/billing/invoices'
    | '/$realmId/manage/billing/payment-providers'
    | '/$realmId/manage/billing/subscriptions'
    | '/$realmId/manage/client-apps/new'
    | '/$realmId/manage/points/default-config'
    | '/$realmId/manage/points/wallets'
    | '/$realmId/subscription/$subscriptionId/history'
    | '/$realmId/user/invoices/new'
    | '/$realmId/user/security/totp-setup'
    | '/$realmId/manage/api-keys/'
    | '/$realmId/manage/audit/'
    | '/$realmId/manage/client-apps/'
    | '/$realmId/user/invoices/'
    | '/$realmId/user/security/'
    | '/$realmId/manage/api-keys/$apiKeyId/edit'
    | '/$realmId/manage/billing/credit-buckets/overview'
    | '/$realmId/manage/billing/invoices/new'
    | '/$realmId/manage/billing/payment-providers/creem'
    | '/$realmId/manage/billing/payment-providers/stripe'
    | '/$realmId/manage/client-apps/$clientAppId/edit'
    | '/$realmId/manage/billing/credit-buckets/'
    | '/$realmId/manage/billing/invoices/'
    | '/$realmId/manage/billing/payment-providers/'
    | '/$realmId/manage/billing/invoices/$invoiceId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$realmId'
    | '/$realmId/auth'
    | '/$realmId/legal'
    | '/$realmId/user'
    | '/$realmId/auth/forgot-password'
    | '/$realmId/auth/login'
    | '/$realmId/auth/register'
    | '/$realmId/auth/reset-password'
    | '/$realmId/auth/verify-email'
    | '/$realmId/device/$userCode'
    | '/$realmId/legal/$agreementType'
    | '/$realmId/manage/billing'
    | '/$realmId/manage/permissions'
    | '/$realmId/manage/points'
    | '/$realmId/manage/realms'
    | '/$realmId/manage/roles'
    | '/$realmId/manage/settings'
    | '/$realmId/manage/subscription'
    | '/$realmId/manage/subscription-history'
    | '/$realmId/manage/users'
    | '/$realmId/subscription/my-subscriptions'
    | '/$realmId/user/points'
    | '/$realmId/user/profile'
    | '/$realmId/user/purchase-points'
    | '/$realmId/user/subscription-history'
    | '/$realmId/device'
    | '/$realmId/manage'
    | '/$realmId/manage/api-keys/new'
    | '/$realmId/manage/api-keys/reveal'
    | '/$realmId/manage/billing/entitlement-mappings'
    | '/$realmId/manage/billing/subscriptions'
    | '/$realmId/manage/client-apps/new'
    | '/$realmId/manage/points/default-config'
    | '/$realmId/manage/points/wallets'
    | '/$realmId/subscription/$subscriptionId/history'
    | '/$realmId/user/invoices/new'
    | '/$realmId/user/security/totp-setup'
    | '/$realmId/manage/api-keys'
    | '/$realmId/manage/audit'
    | '/$realmId/manage/client-apps'
    | '/$realmId/user/invoices'
    | '/$realmId/user/security'
    | '/$realmId/manage/api-keys/$apiKeyId/edit'
    | '/$realmId/manage/billing/credit-buckets/overview'
    | '/$realmId/manage/billing/invoices/new'
    | '/$realmId/manage/billing/payment-providers/creem'
    | '/$realmId/manage/billing/payment-providers/stripe'
    | '/$realmId/manage/client-apps/$clientAppId/edit'
    | '/$realmId/manage/billing/credit-buckets'
    | '/$realmId/manage/billing/invoices'
    | '/$realmId/manage/billing/payment-providers'
    | '/$realmId/manage/billing/invoices/$invoiceId/edit'
  id:
    | '__root__'
    | '/'
    | '/$realmId'
    | '/$realmId/auth'
    | '/$realmId/legal'
    | '/$realmId/manage'
    | '/$realmId/user'
    | '/$realmId/device'
    | '/$realmId/auth/forgot-password'
    | '/$realmId/auth/login'
    | '/$realmId/auth/register'
    | '/$realmId/auth/reset-password'
    | '/$realmId/auth/verify-email'
    | '/$realmId/device/$userCode'
    | '/$realmId/legal/$agreementType'
    | '/$realmId/manage/api-keys'
    | '/$realmId/manage/billing'
    | '/$realmId/manage/client-apps'
    | '/$realmId/manage/permissions'
    | '/$realmId/manage/points'
    | '/$realmId/manage/realms'
    | '/$realmId/manage/roles'
    | '/$realmId/manage/settings'
    | '/$realmId/manage/subscription'
    | '/$realmId/manage/subscription-history'
    | '/$realmId/manage/users'
    | '/$realmId/subscription/my-subscriptions'
    | '/$realmId/user/invoices'
    | '/$realmId/user/points'
    | '/$realmId/user/profile'
    | '/$realmId/user/purchase-points'
    | '/$realmId/user/security'
    | '/$realmId/user/subscription-history'
    | '/$realmId/device/'
    | '/$realmId/manage/'
    | '/$realmId/manage/api-keys/new'
    | '/$realmId/manage/api-keys/reveal'
    | '/$realmId/manage/billing/credit-buckets'
    | '/$realmId/manage/billing/entitlement-mappings'
    | '/$realmId/manage/billing/invoices'
    | '/$realmId/manage/billing/payment-providers'
    | '/$realmId/manage/billing/subscriptions'
    | '/$realmId/manage/client-apps/new'
    | '/$realmId/manage/points/default-config'
    | '/$realmId/manage/points/wallets'
    | '/$realmId/subscription/$subscriptionId/history'
    | '/$realmId/user/invoices/new'
    | '/$realmId/user/security/totp-setup'
    | '/$realmId/manage/api-keys/'
    | '/$realmId/manage/audit/'
    | '/$realmId/manage/client-apps/'
    | '/$realmId/user/invoices/'
    | '/$realmId/user/security/'
    | '/$realmId/manage/api-keys/$apiKeyId/edit'
    | '/$realmId/manage/billing/credit-buckets/overview'
    | '/$realmId/manage/billing/invoices/new'
    | '/$realmId/manage/billing/payment-providers/creem'
    | '/$realmId/manage/billing/payment-providers/stripe'
    | '/$realmId/manage/client-apps/$clientAppId/edit'
    | '/$realmId/manage/billing/credit-buckets/'
    | '/$realmId/manage/billing/invoices/'
    | '/$realmId/manage/billing/payment-providers/'
    | '/$realmId/manage/billing/invoices/$invoiceId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RealmIdRouteRoute: typeof RealmIdRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$realmId': {
      id: '/$realmId'
      path: '/$realmId'
      fullPath: '/$realmId'
      preLoaderRoute: typeof RealmIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$realmId/device': {
      id: '/$realmId/device'
      path: '/device'
      fullPath: '/$realmId/device'
      preLoaderRoute: typeof RealmIdDeviceRouteImport
      parentRoute: typeof RealmIdRouteRoute
    }
    '/$realmId/user': {
      id: '/$realmId/user'
      path: '/user'
      fullPath: '/$realmId/user'
      preLoaderRoute: typeof RealmIdUserRouteRouteImport
      parentRoute: typeof RealmIdRouteRoute
    }
    '/$realmId/manage': {
      id: '/$realmId/manage'
      path: '/manage'
      fullPath: '/$realmId/manage'
      preLoaderRoute: typeof RealmIdManageRouteRouteImport
      parentRoute: typeof RealmIdRouteRoute
    }
    '/$realmId/legal': {
      id: '/$realmId/legal'
      path: '/legal'
      fullPath: '/$realmId/legal'
      preLoaderRoute: typeof RealmIdLegalRouteRouteImport
      parentRoute: typeof RealmIdRouteRoute
    }
    '/$realmId/auth': {
      id: '/$realmId/auth'
      path: '/auth'
      fullPath: '/$realmId/auth'
      preLoaderRoute: typeof RealmIdAuthRouteRouteImport
      parentRoute: typeof RealmIdRouteRoute
    }
    '/$realmId/manage/': {
      id: '/$realmId/manage/'
      path: '/'
      fullPath: '/$realmId/manage/'
      preLoaderRoute: typeof RealmIdManageIndexRouteImport
      parentRoute: typeof RealmIdManageRouteRoute
    }
    '/$realmId/device/': {
      id: '/$realmId/device/'
      path: '/'
      fullPath: '/$realmId/device/'
      preLoaderRoute: typeof RealmIdDeviceIndexRouteImport
      parentRoute: typeof RealmIdDeviceRoute
    }
    '/$realmId/user/subscription-history': {
      id: '/$realmId/user/subscription-history'
      path: '/subscription-history'
      fullPath: '/$realmId/user/subscription-history'
      preLoaderRoute: typeof RealmIdUserSubscriptionHistoryRouteImport
      parentRoute: typeof RealmIdUserRouteRoute
    }
    '/$realmId/user/security': {
      id: '/$realmId/user/security'
      path: '/security'
      fullPath: '/$realmId/user/security'
      preLoaderRoute: typeof RealmIdUserSecurityRouteImport
      parentRoute: typeof RealmIdUserRouteRoute
    }
    '/$realmId/user/purchase-points': {
      id: '/$realmId/user/purchase-points'
      path: '/purchase-points'
      fullPath: '/$realmId/user/purchase-points'
      preLoaderRoute: typeof RealmIdUserPurchasePointsRouteImport
      parentRoute: typeof RealmIdUserRouteRoute
    }
    '/$realmId/user/profile': {
      id: '/$realmId/user/profile'
      path: '/profile'
      fullPath: '/$realmId/user/profile'
      preLoaderRoute: typeof RealmIdUserProfileRouteImport
      parentRoute: typeof RealmIdUserRouteRoute
    }
    '/$realmId/user/points': {
      id: '/$realmId/user/points'
      path: '/points'
      fullPath: '/$realmId/user/points'
      preLoaderRoute: typeof RealmIdUserPointsRouteImport
      parentRoute: typeof RealmIdUserRouteRoute
    }
    '/$realmId/user/invoices': {
      id: '/$realmId/user/invoices'
      path: '/invoices'
      fullPath: '/$realmId/user/invoices'
      preLoaderRoute: typeof RealmIdUserInvoicesRouteImport
      parentRoute: typeof RealmIdUserRouteRoute
    }
    '/$realmId/subscription/my-subscriptions': {
      id: '/$realmId/subscription/my-subscriptions'
      path: '/subscription/my-subscriptions'
      fullPath: '/$realmId/subscription/my-subscriptions'
      preLoaderRoute: typeof RealmIdSubscriptionMySubscriptionsRouteImport
      parentRoute: typeof RealmIdRouteRoute
    }
    '/$realmId/manage/users': {
      id: '/$realmId/manage/users'
      path: '/users'
      fullPath: '/$realmId/manage/users'
      preLoaderRoute: typeof RealmIdManageUsersRouteImport
      parentRoute: typeof RealmIdManageRouteRoute
    }
    '/$realmId/manage/subscription-history': {
      id: '/$realmId/manage/subscription-history'
      path: '/subscription-history'
      fullPath: '/$realmId/manage/subscription-history'
      preLoaderRoute: typeof RealmIdManageSubscriptionHistoryRouteImport
      parentRoute: typeof RealmIdManageRouteRoute
    }
    '/$realmId/manage/subscription': {
      id: '/$realmId/manage/subscription'
      path: '/subscription'
      fullPath: '/$realmId/manage/subscription'
      preLoaderRoute: typeof RealmIdManageSubscriptionRouteImport
      parentRoute: typeof RealmIdManageRouteRoute
    }
    '/$realmId/manage/settings': {
      id: '/$realmId/manage/settings'
      path: '/settings'
      fullPath: '/$realmId/manage/settings'
      preLoaderRoute: typeof RealmIdManageSettingsRouteImport
      parentRoute: typeof RealmIdManageRouteRoute
    }
    '/$realmId/manage/roles': {
      id: '/$realmId/manage/roles'
      path: '/roles'
      fullPath: '/$realmId/manage/roles'
      preLoaderRoute: typeof RealmIdManageRolesRouteImport
      parentRoute: typeof RealmIdManageRouteRoute
    }
    '/$realmId/manage/realms': {
      id: '/$realmId/manage/realms'
      path: '/realms'
      fullPath: '/$realmId/manage/realms'
      preLoaderRoute: typeof RealmIdManageRealmsRouteImport
      parentRoute: typeof RealmIdManageRouteRoute
    }
    '/$realmId/manage/points': {
      id: '/$realmId/manage/points'
      path: '/points'
      fullPath: '/$realmId/manage/points'
      preLoaderRoute: typeof RealmIdManagePointsRouteImport
      parentRoute: typeof RealmIdManageRouteRoute
    }
    '/$realmId/manage/permissions': {
      id: '/$realmId/manage/permissions'
      path: '/permissions'
      fullPath: '/$realmId/manage/permissions'
      preLoaderRoute: typeof RealmIdManagePermissionsRouteImport
      parentRoute: typeof RealmIdManageRouteRoute
    }
    '/$realmId/manage/client-apps': {
      id: '/$realmId/manage/client-apps'
      path: '/client-apps'
      fullPath: '/$realmId/manage/client-apps'
      preLoaderRoute: typeof RealmIdManageClientAppsRouteImport
      parentRoute: typeof RealmIdManageRouteRoute
    }
    '/$realmId/manage/billing': {
      id: '/$realmId/manage/billing'
      path: '/billing'
      fullPath: '/$realmId/manage/billing'
      preLoaderRoute: typeof RealmIdManageBillingRouteImport
      parentRoute: typeof RealmIdManageRouteRoute
    }
    '/$realmId/manage/api-keys': {
      id: '/$realmId/manage/api-keys'
      path: '/api-keys'
      fullPath: '/$realmId/manage/api-keys'
      preLoaderRoute: typeof RealmIdManageApiKeysRouteImport
      parentRoute: typeof RealmIdManageRouteRoute
    }
    '/$realmId/legal/$agreementType': {
      id: '/$realmId/legal/$agreementType'
      path: '/$agreementType'
      fullPath: '/$realmId/legal/$agreementType'
      preLoaderRoute: typeof RealmIdLegalAgreementTypeRouteImport
      parentRoute: typeof RealmIdLegalRouteRoute
    }
    '/$realmId/device/$userCode': {
      id: '/$realmId/device/$userCode'
      path: '/$userCode'
      fullPath: '/$realmId/device/$userCode'
      preLoaderRoute: typeof RealmIdDeviceUserCodeRouteImport
      parentRoute: typeof RealmIdDeviceRoute
    }
    '/$realmId/auth/verify-email': {
      id: '/$realmId/auth/verify-email'
      path: '/verify-email'
      fullPath: '/$realmId/auth/verify-email'
      preLoaderRoute: typeof RealmIdAuthVerifyEmailRouteImport
      parentRoute: typeof RealmIdAuthRouteRoute
    }
    '/$realmId/auth/reset-password': {
      id: '/$realmId/auth/reset-password'
      path: '/reset-password'
      fullPath: '/$realmId/auth/reset-password'
      preLoaderRoute: typeof RealmIdAuthResetPasswordRouteImport
      parentRoute: typeof RealmIdAuthRouteRoute
    }
    '/$realmId/auth/register': {
      id: '/$realmId/auth/register'
      path: '/register'
      fullPath: '/$realmId/auth/register'
      preLoaderRoute: typeof RealmIdAuthRegisterRouteImport
      parentRoute: typeof RealmIdAuthRouteRoute
    }
    '/$realmId/auth/login': {
      id: '/$realmId/auth/login'
      path: '/login'
      fullPath: '/$realmId/auth/login'
      preLoaderRoute: typeof RealmIdAuthLoginRouteImport
      parentRoute: typeof RealmIdAuthRouteRoute
    }
    '/$realmId/auth/forgot-password': {
      id: '/$realmId/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/$realmId/auth/forgot-password'
      preLoaderRoute: typeof RealmIdAuthForgotPasswordRouteImport
      parentRoute: typeof RealmIdAuthRouteRoute
    }
    '/$realmId/user/security/': {
      id: '/$realmId/user/security/'
      path: '/'
      fullPath: '/$realmId/user/security/'
      preLoaderRoute: typeof RealmIdUserSecurityIndexRouteImport
      parentRoute: typeof RealmIdUserSecurityRoute
    }
    '/$realmId/user/invoices/': {
      id: '/$realmId/user/invoices/'
      path: '/'
      fullPath: '/$realmId/user/invoices/'
      preLoaderRoute: typeof RealmIdUserInvoicesIndexRouteImport
      parentRoute: typeof RealmIdUserInvoicesRoute
    }
    '/$realmId/manage/client-apps/': {
      id: '/$realmId/manage/client-apps/'
      path: '/'
      fullPath: '/$realmId/manage/client-apps/'
      preLoaderRoute: typeof RealmIdManageClientAppsIndexRouteImport
      parentRoute: typeof RealmIdManageClientAppsRoute
    }
    '/$realmId/manage/audit/': {
      id: '/$realmId/manage/audit/'
      path: '/audit'
      fullPath: '/$realmId/manage/audit/'
      preLoaderRoute: typeof RealmIdManageAuditIndexRouteImport
      parentRoute: typeof RealmIdManageRouteRoute
    }
    '/$realmId/manage/api-keys/': {
      id: '/$realmId/manage/api-keys/'
      path: '/'
      fullPath: '/$realmId/manage/api-keys/'
      preLoaderRoute: typeof RealmIdManageApiKeysIndexRouteImport
      parentRoute: typeof RealmIdManageApiKeysRoute
    }
    '/$realmId/user/security/totp-setup': {
      id: '/$realmId/user/security/totp-setup'
      path: '/totp-setup'
      fullPath: '/$realmId/user/security/totp-setup'
      preLoaderRoute: typeof RealmIdUserSecurityTotpSetupRouteImport
      parentRoute: typeof RealmIdUserSecurityRoute
    }
    '/$realmId/user/invoices/new': {
      id: '/$realmId/user/invoices/new'
      path: '/new'
      fullPath: '/$realmId/user/invoices/new'
      preLoaderRoute: typeof RealmIdUserInvoicesNewRouteImport
      parentRoute: typeof RealmIdUserInvoicesRoute
    }
    '/$realmId/subscription/$subscriptionId/history': {
      id: '/$realmId/subscription/$subscriptionId/history'
      path: '/subscription/$subscriptionId/history'
      fullPath: '/$realmId/subscription/$subscriptionId/history'
      preLoaderRoute: typeof RealmIdSubscriptionSubscriptionIdHistoryRouteImport
      parentRoute: typeof RealmIdRouteRoute
    }
    '/$realmId/manage/points/wallets': {
      id: '/$realmId/manage/points/wallets'
      path: '/wallets'
      fullPath: '/$realmId/manage/points/wallets'
      preLoaderRoute: typeof RealmIdManagePointsWalletsRouteImport
      parentRoute: typeof RealmIdManagePointsRoute
    }
    '/$realmId/manage/points/default-config': {
      id: '/$realmId/manage/points/default-config'
      path: '/default-config'
      fullPath: '/$realmId/manage/points/default-config'
      preLoaderRoute: typeof RealmIdManagePointsDefaultConfigRouteImport
      parentRoute: typeof RealmIdManagePointsRoute
    }
    '/$realmId/manage/client-apps/new': {
      id: '/$realmId/manage/client-apps/new'
      path: '/new'
      fullPath: '/$realmId/manage/client-apps/new'
      preLoaderRoute: typeof RealmIdManageClientAppsNewRouteImport
      parentRoute: typeof RealmIdManageClientAppsRoute
    }
    '/$realmId/manage/billing/subscriptions': {
      id: '/$realmId/manage/billing/subscriptions'
      path: '/subscriptions'
      fullPath: '/$realmId/manage/billing/subscriptions'
      preLoaderRoute: typeof RealmIdManageBillingSubscriptionsRouteImport
      parentRoute: typeof RealmIdManageBillingRoute
    }
    '/$realmId/manage/billing/payment-providers': {
      id: '/$realmId/manage/billing/payment-providers'
      path: '/payment-providers'
      fullPath: '/$realmId/manage/billing/payment-providers'
      preLoaderRoute: typeof RealmIdManageBillingPaymentProvidersRouteImport
      parentRoute: typeof RealmIdManageBillingRoute
    }
    '/$realmId/manage/billing/invoices': {
      id: '/$realmId/manage/billing/invoices'
      path: '/invoices'
      fullPath: '/$realmId/manage/billing/invoices'
      preLoaderRoute: typeof RealmIdManageBillingInvoicesRouteImport
      parentRoute: typeof RealmIdManageBillingRoute
    }
    '/$realmId/manage/billing/entitlement-mappings': {
      id: '/$realmId/manage/billing/entitlement-mappings'
      path: '/entitlement-mappings'
      fullPath: '/$realmId/manage/billing/entitlement-mappings'
      preLoaderRoute: typeof RealmIdManageBillingEntitlementMappingsRouteImport
      parentRoute: typeof RealmIdManageBillingRoute
    }
    '/$realmId/manage/billing/credit-buckets': {
      id: '/$realmId/manage/billing/credit-buckets'
      path: '/credit-buckets'
      fullPath: '/$realmId/manage/billing/credit-buckets'
      preLoaderRoute: typeof RealmIdManageBillingCreditBucketsRouteImport
      parentRoute: typeof RealmIdManageBillingRoute
    }
    '/$realmId/manage/api-keys/reveal': {
      id: '/$realmId/manage/api-keys/reveal'
      path: '/reveal'
      fullPath: '/$realmId/manage/api-keys/reveal'
      preLoaderRoute: typeof RealmIdManageApiKeysRevealRouteImport
      parentRoute: typeof RealmIdManageApiKeysRoute
    }
    '/$realmId/manage/api-keys/new': {
      id: '/$realmId/manage/api-keys/new'
      path: '/new'
      fullPath: '/$realmId/manage/api-keys/new'
      preLoaderRoute: typeof RealmIdManageApiKeysNewRouteImport
      parentRoute: typeof RealmIdManageApiKeysRoute
    }
    '/$realmId/manage/billing/payment-providers/': {
      id: '/$realmId/manage/billing/payment-providers/'
      path: '/'
      fullPath: '/$realmId/manage/billing/payment-providers/'
      preLoaderRoute: typeof RealmIdManageBillingPaymentProvidersIndexRouteImport
      parentRoute: typeof RealmIdManageBillingPaymentProvidersRoute
    }
    '/$realmId/manage/billing/invoices/': {
      id: '/$realmId/manage/billing/invoices/'
      path: '/'
      fullPath: '/$realmId/manage/billing/invoices/'
      preLoaderRoute: typeof RealmIdManageBillingInvoicesIndexRouteImport
      parentRoute: typeof RealmIdManageBillingInvoicesRoute
    }
    '/$realmId/manage/billing/credit-buckets/': {
      id: '/$realmId/manage/billing/credit-buckets/'
      path: '/'
      fullPath: '/$realmId/manage/billing/credit-buckets/'
      preLoaderRoute: typeof RealmIdManageBillingCreditBucketsIndexRouteImport
      parentRoute: typeof RealmIdManageBillingCreditBucketsRoute
    }
    '/$realmId/manage/client-apps/$clientAppId/edit': {
      id: '/$realmId/manage/client-apps/$clientAppId/edit'
      path: '/$clientAppId/edit'
      fullPath: '/$realmId/manage/client-apps/$clientAppId/edit'
      preLoaderRoute: typeof RealmIdManageClientAppsClientAppIdEditRouteImport
      parentRoute: typeof RealmIdManageClientAppsRoute
    }
    '/$realmId/manage/billing/payment-providers/stripe': {
      id: '/$realmId/manage/billing/payment-providers/stripe'
      path: '/stripe'
      fullPath: '/$realmId/manage/billing/payment-providers/stripe'
      preLoaderRoute: typeof RealmIdManageBillingPaymentProvidersStripeRouteImport
      parentRoute: typeof RealmIdManageBillingPaymentProvidersRoute
    }
    '/$realmId/manage/billing/payment-providers/creem': {
      id: '/$realmId/manage/billing/payment-providers/creem'
      path: '/creem'
      fullPath: '/$realmId/manage/billing/payment-providers/creem'
      preLoaderRoute: typeof RealmIdManageBillingPaymentProvidersCreemRouteImport
      parentRoute: typeof RealmIdManageBillingPaymentProvidersRoute
    }
    '/$realmId/manage/billing/invoices/new': {
      id: '/$realmId/manage/billing/invoices/new'
      path: '/new'
      fullPath: '/$realmId/manage/billing/invoices/new'
      preLoaderRoute: typeof RealmIdManageBillingInvoicesNewRouteImport
      parentRoute: typeof RealmIdManageBillingInvoicesRoute
    }
    '/$realmId/manage/billing/credit-buckets/overview': {
      id: '/$realmId/manage/billing/credit-buckets/overview'
      path: '/overview'
      fullPath: '/$realmId/manage/billing/credit-buckets/overview'
      preLoaderRoute: typeof RealmIdManageBillingCreditBucketsOverviewRouteImport
      parentRoute: typeof RealmIdManageBillingCreditBucketsRoute
    }
    '/$realmId/manage/api-keys/$apiKeyId/edit': {
      id: '/$realmId/manage/api-keys/$apiKeyId/edit'
      path: '/$apiKeyId/edit'
      fullPath: '/$realmId/manage/api-keys/$apiKeyId/edit'
      preLoaderRoute: typeof RealmIdManageApiKeysApiKeyIdEditRouteImport
      parentRoute: typeof RealmIdManageApiKeysRoute
    }
    '/$realmId/manage/billing/invoices/$invoiceId/edit': {
      id: '/$realmId/manage/billing/invoices/$invoiceId/edit'
      path: '/$invoiceId/edit'
      fullPath: '/$realmId/manage/billing/invoices/$invoiceId/edit'
      preLoaderRoute: typeof RealmIdManageBillingInvoicesInvoiceIdEditRouteImport
      parentRoute: typeof RealmIdManageBillingInvoicesRoute
    }
  }
}

interface RealmIdAuthRouteRouteChildren {
  RealmIdAuthForgotPasswordRoute: typeof RealmIdAuthForgotPasswordRoute
  RealmIdAuthLoginRoute: typeof RealmIdAuthLoginRoute
  RealmIdAuthRegisterRoute: typeof RealmIdAuthRegisterRoute
  RealmIdAuthResetPasswordRoute: typeof RealmIdAuthResetPasswordRoute
  RealmIdAuthVerifyEmailRoute: typeof RealmIdAuthVerifyEmailRoute
}

const RealmIdAuthRouteRouteChildren: RealmIdAuthRouteRouteChildren = {
  RealmIdAuthForgotPasswordRoute: RealmIdAuthForgotPasswordRoute,
  RealmIdAuthLoginRoute: RealmIdAuthLoginRoute,
  RealmIdAuthRegisterRoute: RealmIdAuthRegisterRoute,
  RealmIdAuthResetPasswordRoute: RealmIdAuthResetPasswordRoute,
  RealmIdAuthVerifyEmailRoute: RealmIdAuthVerifyEmailRoute,
}

const RealmIdAuthRouteRouteWithChildren =
  RealmIdAuthRouteRoute._addFileChildren(RealmIdAuthRouteRouteChildren)

interface RealmIdLegalRouteRouteChildren {
  RealmIdLegalAgreementTypeRoute: typeof RealmIdLegalAgreementTypeRoute
}

const RealmIdLegalRouteRouteChildren: RealmIdLegalRouteRouteChildren = {
  RealmIdLegalAgreementTypeRoute: RealmIdLegalAgreementTypeRoute,
}

const RealmIdLegalRouteRouteWithChildren =
  RealmIdLegalRouteRoute._addFileChildren(RealmIdLegalRouteRouteChildren)

interface RealmIdManageApiKeysRouteChildren {
  RealmIdManageApiKeysNewRoute: typeof RealmIdManageApiKeysNewRoute
  RealmIdManageApiKeysRevealRoute: typeof RealmIdManageApiKeysRevealRoute
  RealmIdManageApiKeysIndexRoute: typeof RealmIdManageApiKeysIndexRoute
  RealmIdManageApiKeysApiKeyIdEditRoute: typeof RealmIdManageApiKeysApiKeyIdEditRoute
}

const RealmIdManageApiKeysRouteChildren: RealmIdManageApiKeysRouteChildren = {
  RealmIdManageApiKeysNewRoute: RealmIdManageApiKeysNewRoute,
  RealmIdManageApiKeysRevealRoute: RealmIdManageApiKeysRevealRoute,
  RealmIdManageApiKeysIndexRoute: RealmIdManageApiKeysIndexRoute,
  RealmIdManageApiKeysApiKeyIdEditRoute: RealmIdManageApiKeysApiKeyIdEditRoute,
}

const RealmIdManageApiKeysRouteWithChildren =
  RealmIdManageApiKeysRoute._addFileChildren(RealmIdManageApiKeysRouteChildren)

interface RealmIdManageBillingCreditBucketsRouteChildren {
  RealmIdManageBillingCreditBucketsOverviewRoute: typeof RealmIdManageBillingCreditBucketsOverviewRoute
  RealmIdManageBillingCreditBucketsIndexRoute: typeof RealmIdManageBillingCreditBucketsIndexRoute
}

const RealmIdManageBillingCreditBucketsRouteChildren: RealmIdManageBillingCreditBucketsRouteChildren =
  {
    RealmIdManageBillingCreditBucketsOverviewRoute:
      RealmIdManageBillingCreditBucketsOverviewRoute,
    RealmIdManageBillingCreditBucketsIndexRoute:
      RealmIdManageBillingCreditBucketsIndexRoute,
  }

const RealmIdManageBillingCreditBucketsRouteWithChildren =
  RealmIdManageBillingCreditBucketsRoute._addFileChildren(
    RealmIdManageBillingCreditBucketsRouteChildren,
  )

interface RealmIdManageBillingInvoicesRouteChildren {
  RealmIdManageBillingInvoicesNewRoute: typeof RealmIdManageBillingInvoicesNewRoute
  RealmIdManageBillingInvoicesIndexRoute: typeof RealmIdManageBillingInvoicesIndexRoute
  RealmIdManageBillingInvoicesInvoiceIdEditRoute: typeof RealmIdManageBillingInvoicesInvoiceIdEditRoute
}

const RealmIdManageBillingInvoicesRouteChildren: RealmIdManageBillingInvoicesRouteChildren =
  {
    RealmIdManageBillingInvoicesNewRoute: RealmIdManageBillingInvoicesNewRoute,
    RealmIdManageBillingInvoicesIndexRoute:
      RealmIdManageBillingInvoicesIndexRoute,
    RealmIdManageBillingInvoicesInvoiceIdEditRoute:
      RealmIdManageBillingInvoicesInvoiceIdEditRoute,
  }

const RealmIdManageBillingInvoicesRouteWithChildren =
  RealmIdManageBillingInvoicesRoute._addFileChildren(
    RealmIdManageBillingInvoicesRouteChildren,
  )

interface RealmIdManageBillingPaymentProvidersRouteChildren {
  RealmIdManageBillingPaymentProvidersCreemRoute: typeof RealmIdManageBillingPaymentProvidersCreemRoute
  RealmIdManageBillingPaymentProvidersStripeRoute: typeof RealmIdManageBillingPaymentProvidersStripeRoute
  RealmIdManageBillingPaymentProvidersIndexRoute: typeof RealmIdManageBillingPaymentProvidersIndexRoute
}

const RealmIdManageBillingPaymentProvidersRouteChildren: RealmIdManageBillingPaymentProvidersRouteChildren =
  {
    RealmIdManageBillingPaymentProvidersCreemRoute:
      RealmIdManageBillingPaymentProvidersCreemRoute,
    RealmIdManageBillingPaymentProvidersStripeRoute:
      RealmIdManageBillingPaymentProvidersStripeRoute,
    RealmIdManageBillingPaymentProvidersIndexRoute:
      RealmIdManageBillingPaymentProvidersIndexRoute,
  }

const RealmIdManageBillingPaymentProvidersRouteWithChildren =
  RealmIdManageBillingPaymentProvidersRoute._addFileChildren(
    RealmIdManageBillingPaymentProvidersRouteChildren,
  )

interface RealmIdManageBillingRouteChildren {
  RealmIdManageBillingCreditBucketsRoute: typeof RealmIdManageBillingCreditBucketsRouteWithChildren
  RealmIdManageBillingEntitlementMappingsRoute: typeof RealmIdManageBillingEntitlementMappingsRoute
  RealmIdManageBillingInvoicesRoute: typeof RealmIdManageBillingInvoicesRouteWithChildren
  RealmIdManageBillingPaymentProvidersRoute: typeof RealmIdManageBillingPaymentProvidersRouteWithChildren
  RealmIdManageBillingSubscriptionsRoute: typeof RealmIdManageBillingSubscriptionsRoute
}

const RealmIdManageBillingRouteChildren: RealmIdManageBillingRouteChildren = {
  RealmIdManageBillingCreditBucketsRoute:
    RealmIdManageBillingCreditBucketsRouteWithChildren,
  RealmIdManageBillingEntitlementMappingsRoute:
    RealmIdManageBillingEntitlementMappingsRoute,
  RealmIdManageBillingInvoicesRoute:
    RealmIdManageBillingInvoicesRouteWithChildren,
  RealmIdManageBillingPaymentProvidersRoute:
    RealmIdManageBillingPaymentProvidersRouteWithChildren,
  RealmIdManageBillingSubscriptionsRoute:
    RealmIdManageBillingSubscriptionsRoute,
}

const RealmIdManageBillingRouteWithChildren =
  RealmIdManageBillingRoute._addFileChildren(RealmIdManageBillingRouteChildren)

interface RealmIdManageClientAppsRouteChildren {
  RealmIdManageClientAppsNewRoute: typeof RealmIdManageClientAppsNewRoute
  RealmIdManageClientAppsIndexRoute: typeof RealmIdManageClientAppsIndexRoute
  RealmIdManageClientAppsClientAppIdEditRoute: typeof RealmIdManageClientAppsClientAppIdEditRoute
}

const RealmIdManageClientAppsRouteChildren: RealmIdManageClientAppsRouteChildren =
  {
    RealmIdManageClientAppsNewRoute: RealmIdManageClientAppsNewRoute,
    RealmIdManageClientAppsIndexRoute: RealmIdManageClientAppsIndexRoute,
    RealmIdManageClientAppsClientAppIdEditRoute:
      RealmIdManageClientAppsClientAppIdEditRoute,
  }

const RealmIdManageClientAppsRouteWithChildren =
  RealmIdManageClientAppsRoute._addFileChildren(
    RealmIdManageClientAppsRouteChildren,
  )

interface RealmIdManagePointsRouteChildren {
  RealmIdManagePointsDefaultConfigRoute: typeof RealmIdManagePointsDefaultConfigRoute
  RealmIdManagePointsWalletsRoute: typeof RealmIdManagePointsWalletsRoute
}

const RealmIdManagePointsRouteChildren: RealmIdManagePointsRouteChildren = {
  RealmIdManagePointsDefaultConfigRoute: RealmIdManagePointsDefaultConfigRoute,
  RealmIdManagePointsWalletsRoute: RealmIdManagePointsWalletsRoute,
}

const RealmIdManagePointsRouteWithChildren =
  RealmIdManagePointsRoute._addFileChildren(RealmIdManagePointsRouteChildren)

interface RealmIdManageRouteRouteChildren {
  RealmIdManageApiKeysRoute: typeof RealmIdManageApiKeysRouteWithChildren
  RealmIdManageBillingRoute: typeof RealmIdManageBillingRouteWithChildren
  RealmIdManageClientAppsRoute: typeof RealmIdManageClientAppsRouteWithChildren
  RealmIdManagePermissionsRoute: typeof RealmIdManagePermissionsRoute
  RealmIdManagePointsRoute: typeof RealmIdManagePointsRouteWithChildren
  RealmIdManageRealmsRoute: typeof RealmIdManageRealmsRoute
  RealmIdManageRolesRoute: typeof RealmIdManageRolesRoute
  RealmIdManageSettingsRoute: typeof RealmIdManageSettingsRoute
  RealmIdManageSubscriptionRoute: typeof RealmIdManageSubscriptionRoute
  RealmIdManageSubscriptionHistoryRoute: typeof RealmIdManageSubscriptionHistoryRoute
  RealmIdManageUsersRoute: typeof RealmIdManageUsersRoute
  RealmIdManageIndexRoute: typeof RealmIdManageIndexRoute
  RealmIdManageAuditIndexRoute: typeof RealmIdManageAuditIndexRoute
}

const RealmIdManageRouteRouteChildren: RealmIdManageRouteRouteChildren = {
  RealmIdManageApiKeysRoute: RealmIdManageApiKeysRouteWithChildren,
  RealmIdManageBillingRoute: RealmIdManageBillingRouteWithChildren,
  RealmIdManageClientAppsRoute: RealmIdManageClientAppsRouteWithChildren,
  RealmIdManagePermissionsRoute: RealmIdManagePermissionsRoute,
  RealmIdManagePointsRoute: RealmIdManagePointsRouteWithChildren,
  RealmIdManageRealmsRoute: RealmIdManageRealmsRoute,
  RealmIdManageRolesRoute: RealmIdManageRolesRoute,
  RealmIdManageSettingsRoute: RealmIdManageSettingsRoute,
  RealmIdManageSubscriptionRoute: RealmIdManageSubscriptionRoute,
  RealmIdManageSubscriptionHistoryRoute: RealmIdManageSubscriptionHistoryRoute,
  RealmIdManageUsersRoute: RealmIdManageUsersRoute,
  RealmIdManageIndexRoute: RealmIdManageIndexRoute,
  RealmIdManageAuditIndexRoute: RealmIdManageAuditIndexRoute,
}

const RealmIdManageRouteRouteWithChildren =
  RealmIdManageRouteRoute._addFileChildren(RealmIdManageRouteRouteChildren)

interface RealmIdUserInvoicesRouteChildren {
  RealmIdUserInvoicesNewRoute: typeof RealmIdUserInvoicesNewRoute
  RealmIdUserInvoicesIndexRoute: typeof RealmIdUserInvoicesIndexRoute
}

const RealmIdUserInvoicesRouteChildren: RealmIdUserInvoicesRouteChildren = {
  RealmIdUserInvoicesNewRoute: RealmIdUserInvoicesNewRoute,
  RealmIdUserInvoicesIndexRoute: RealmIdUserInvoicesIndexRoute,
}

const RealmIdUserInvoicesRouteWithChildren =
  RealmIdUserInvoicesRoute._addFileChildren(RealmIdUserInvoicesRouteChildren)

interface RealmIdUserSecurityRouteChildren {
  RealmIdUserSecurityTotpSetupRoute: typeof RealmIdUserSecurityTotpSetupRoute
  RealmIdUserSecurityIndexRoute: typeof RealmIdUserSecurityIndexRoute
}

const RealmIdUserSecurityRouteChildren: RealmIdUserSecurityRouteChildren = {
  RealmIdUserSecurityTotpSetupRoute: RealmIdUserSecurityTotpSetupRoute,
  RealmIdUserSecurityIndexRoute: RealmIdUserSecurityIndexRoute,
}

const RealmIdUserSecurityRouteWithChildren =
  RealmIdUserSecurityRoute._addFileChildren(RealmIdUserSecurityRouteChildren)

interface RealmIdUserRouteRouteChildren {
  RealmIdUserInvoicesRoute: typeof RealmIdUserInvoicesRouteWithChildren
  RealmIdUserPointsRoute: typeof RealmIdUserPointsRoute
  RealmIdUserProfileRoute: typeof RealmIdUserProfileRoute
  RealmIdUserPurchasePointsRoute: typeof RealmIdUserPurchasePointsRoute
  RealmIdUserSecurityRoute: typeof RealmIdUserSecurityRouteWithChildren
  RealmIdUserSubscriptionHistoryRoute: typeof RealmIdUserSubscriptionHistoryRoute
}

const RealmIdUserRouteRouteChildren: RealmIdUserRouteRouteChildren = {
  RealmIdUserInvoicesRoute: RealmIdUserInvoicesRouteWithChildren,
  RealmIdUserPointsRoute: RealmIdUserPointsRoute,
  RealmIdUserProfileRoute: RealmIdUserProfileRoute,
  RealmIdUserPurchasePointsRoute: RealmIdUserPurchasePointsRoute,
  RealmIdUserSecurityRoute: RealmIdUserSecurityRouteWithChildren,
  RealmIdUserSubscriptionHistoryRoute: RealmIdUserSubscriptionHistoryRoute,
}

const RealmIdUserRouteRouteWithChildren =
  RealmIdUserRouteRoute._addFileChildren(RealmIdUserRouteRouteChildren)

interface RealmIdDeviceRouteChildren {
  RealmIdDeviceUserCodeRoute: typeof RealmIdDeviceUserCodeRoute
  RealmIdDeviceIndexRoute: typeof RealmIdDeviceIndexRoute
}

const RealmIdDeviceRouteChildren: RealmIdDeviceRouteChildren = {
  RealmIdDeviceUserCodeRoute: RealmIdDeviceUserCodeRoute,
  RealmIdDeviceIndexRoute: RealmIdDeviceIndexRoute,
}

const RealmIdDeviceRouteWithChildren = RealmIdDeviceRoute._addFileChildren(
  RealmIdDeviceRouteChildren,
)

interface RealmIdRouteRouteChildren {
  RealmIdAuthRouteRoute: typeof RealmIdAuthRouteRouteWithChildren
  RealmIdLegalRouteRoute: typeof RealmIdLegalRouteRouteWithChildren
  RealmIdManageRouteRoute: typeof RealmIdManageRouteRouteWithChildren
  RealmIdUserRouteRoute: typeof RealmIdUserRouteRouteWithChildren
  RealmIdDeviceRoute: typeof RealmIdDeviceRouteWithChildren
  RealmIdSubscriptionMySubscriptionsRoute: typeof RealmIdSubscriptionMySubscriptionsRoute
  RealmIdSubscriptionSubscriptionIdHistoryRoute: typeof RealmIdSubscriptionSubscriptionIdHistoryRoute
}

const RealmIdRouteRouteChildren: RealmIdRouteRouteChildren = {
  RealmIdAuthRouteRoute: RealmIdAuthRouteRouteWithChildren,
  RealmIdLegalRouteRoute: RealmIdLegalRouteRouteWithChildren,
  RealmIdManageRouteRoute: RealmIdManageRouteRouteWithChildren,
  RealmIdUserRouteRoute: RealmIdUserRouteRouteWithChildren,
  RealmIdDeviceRoute: RealmIdDeviceRouteWithChildren,
  RealmIdSubscriptionMySubscriptionsRoute:
    RealmIdSubscriptionMySubscriptionsRoute,
  RealmIdSubscriptionSubscriptionIdHistoryRoute:
    RealmIdSubscriptionSubscriptionIdHistoryRoute,
}

const RealmIdRouteRouteWithChildren = RealmIdRouteRoute._addFileChildren(
  RealmIdRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RealmIdRouteRoute: RealmIdRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
